INSERT INTO knowledge_items (code, description) VALUES
('K1171', 'Knowledge of mission assurance practices and principles'),
('K1172', 'Knowledge of mission requirements'),
('K1173', 'Knowledge of multilevel security requirements'),
('K1174', 'Knowledge of network components'),
('K1175', 'Knowledge of network monitoring tools and techniques'),
('K1176', 'Knowledge of network topologies'),
('K1178', 'Knowledge of operational environment risks'),
('K1179', 'Knowledge of organization''s security strategy'),
('K1180', 'Knowledge of organizational cybersecurity goals and objectives'),
('K1181', 'Knowledge of organizational cybersecurity incident response plans'),
('K1182', 'Knowledge of organizational cybersecurity policies and configurations'),
('K1183', 'Knowledge of organizational cybersecurity policies and procedures'),
('K1184', 'Knowledge of organizational cybersecurity workforce requirements'),
('K1185', 'Knowledge of organizational evaluation and validation requirements'),
('K1186', 'Knowledge of organizational human resource (HR) policies and procedures'),
('K1187', 'Knowledge of organizational objectives'),
('K1188', 'Knowledge of organizational policies and procedures'),
('K1189', 'Knowledge of organizational policy and procedures'),
('K1190', 'Knowledge of organizational risk levels'),
('K1191', 'Knowledge of organizational security posture'),
('K1192', 'Knowledge of organizational privacy policies and procedures'),
('K1193', 'Knowledge of packet analysis tools and techniques'),
('K1194', 'Knowledge of Personally Identifiable Information (PII) attributes'),
('K1195', 'Knowledge of priority information requirements'),
('K1197', 'Knowledge of priority intelligence requirements'),
('K1198', 'Knowledge of privacy and data security regulators'),
('K1200', 'Knowledge of privacy technologies'),
('K1201', 'Knowledge of programming languages'),
('K1202', 'Knowledge of project plans and schedules'),
('K1203', 'Knowledge of Public Key Infrastructure (PKI) libraries'),
('K1205', 'Knowledge of required reporting formats'),
('K1206', 'Knowledge of research and design processes and procedures'),
('K1207', 'Knowledge of reverse engineering tools and techniques'),
('K1208', 'Knowledge of risk acceptance and documentation'),
('K1209', 'Knowledge of risk mitigation principles and practices'),
('K1210', 'Knowledge of secure programming tools and techniques'),
('K1211', 'Knowledge of security assessment authorization requirements'),
('K1212', 'Knowledge of security controls'),
('K1213', 'Knowledge of security requirements'),
('K1214', 'Knowledge of security restrictions'),
('K1215', 'Knowledge of security testing tools and techniques'),
('K1216', 'Knowledge of service-oriented security architecture practices and principles'),
('K1217', 'Knowledge of software and systems engineering life cycle standards'),
('K1218', 'Knowledge of software application, system, and network requirements'),
('K1219', 'Knowledge of statistical processes'),
('K1220', 'Knowledge of steganography practices and principles'),
('K1221', 'Knowledge of supply chain risk management practices'),
('K1222', 'Knowledge of system availability requirements'),
('K1223', 'Knowledge of system backup requirements'),
('K1224', 'Knowledge of system characteristics'),
('K1225', 'Knowledge of system life cycles'),
('K1226', 'Knowledge of systems administration standard operating policies and procedures'),
('K1227', 'Knowledge of systems architecture'),
('K1228', 'Knowledge of systems development'),
('K1233', 'Knowledge of UNIX scripts'),
('K1234', 'Knowledge of user interfaces'),
('K1235', 'Knowledge of user needs and requirements'),
('K1236', 'Knowledge of user requirements'),
('K1237', 'Knowledge of Virtual Private Network (VPN) devices'),
('K1238', 'Knowledge of Windows scripts'),
('K1239', 'Knowledge of certificate management principles and practices'),
('K1240', 'Knowledge of privacy laws and regulations'),
('K1241', 'Knowledge of cultural, political, and organizational assets'),
('K1242', 'Knowledge of cybersecurity review processes and procedures'),
('K1243', 'Knowledge of cybersecurity threat remediation principles and practices'),
('K1244', 'Knowledge of cybersecurity tools and techniques'),
('K1245', 'Knowledge of data exfiltration tools and techniques'),
('K1246', 'Knowledge of data handling tools and techniques'),
('K1247', 'Knowledge of data monitoring tools and techniques'),
('K1248', 'Knowledge of digital and physical security vulnerabilities'),
('K1249', 'Knowledge of digital and physical security vulnerability remediation principles and practices'),
('K1250', 'Knowledge of external organization roles and responsibilities'),
('K1251', 'Knowledge of external referrals policies and procedures'),
('K1252', 'Knowledge of high value asset characteristics'),
('K1253', 'Knowledge of information collection tools and techniques'),
('K1254', 'Knowledge of insider threat hub policies and procedures'),
('K1255', 'Knowledge of insider threat hub operations'),
('K1256', 'Knowledge of insider threat operational indicators'),
('K1257', 'Knowledge of insider threat policies and procedures'),
('K1258', 'Knowledge of insider threat tactics'),
('K1259', 'Knowledge of insider threat targets'),
('K1260', 'Knowledge of intelligence laws and regulations'),
('K1261', 'Knowledge of known insider attacks'),
('K1262', 'Knowledge of network endpoints'),
('K1263', 'Knowledge of notification policies and procedures'),
('K1265', 'Knowledge of organizational objectives, resources, and capabilities'),
('K1267', 'Knowledge of previously referred potential insider threats'),
('K1268', 'Knowledge of risk reduction metrics'),
('K1269', 'Knowledge of security information and event management (SIEM) tools and techniques'),
('K1270', 'Knowledge of suspicious activity response processes'),
('K1271', 'Knowledge of system alert policies and procedures'),
('K1272', 'Knowledge of system components'),
('K1273', 'Knowledge of threat investigation policies and procedures'),
('K1274', 'Knowledge of threat modeling tools and techniques'),
('K1275', 'Knowledge of User Activity Monitoring (UAM) tools and techniques'),
('K1276', 'Knowledge of advanced persistent threats (APTs)'),
('K1277', 'Knowledge of cyber resiliency goals and objectives'),
('K1278', 'Knowledge of data vaulting principles and practices'),
('K1279', 'Knowledge of threat-informed defense'),
('K1280', 'Knowledge of approved data processing tools and techniques'),
('K1281', 'Knowledge of data types and characteristics'),
('K1282', 'Knowledge of predication requirements'),
('K1283', 'Knowledge of court exhibit processes'),
('K1284', 'Knowledge of testing and calibration in laboratory environment'),
('K1285', 'Knowledge of assessment remediation requirements'),
('K1286', 'Knowledge of Business Impact Analysis (BIA)'),
('K1287', 'Knowledge of change management processes'),
('K1288', 'Knowledge of OT cybersecurity compliance requirements and best practices'),
('K1289', 'Knowledge of control system environment risks, threats, and vulnerabilities'),
('K1290', 'Knowledge of the Active Cyber Defense Cycle (ACDC)'),
('K1291', 'Knowledge of active defense principles and practices'),
('K1292', 'Knowledge of OT cybersecurity risk tolerance levels'),
('K1293', 'Knowledge of Purdue Model levels'),
('K1294', 'Knowledge of change management policies and procedures'),
('K1295', 'Knowledge of OT cybersecurity inspection and testing policies and procedures'),
('K1296', 'Knowledge of control system policies and procedures'),
('K1297', 'Knowledge of OT safety systems'),
('K1298', 'Knowledge of anomaly detection tools and techniques'),
('K1299', 'Knowledge of change management processes'),
('K1300', 'Knowledge of control system network architectures'),
('K1301', 'Knowledge of cyber incidents impacting OT'),
('K1302', 'Knowledge of industry hazards'),
('K1303', 'Knowledge of life cycle management principles and practices'),
('K1304', 'Knowledge of operational priorities'),
('K1305', 'Knowledge of OT asset management tools and techniques'),
('K1306', 'Knowledge of OT assets'),
('K1307', 'Knowledge of OT inventory principles and practices'),
('K1308', 'Knowledge of OT network detection tools and techniques'),
('K1309', 'Knowledge of OT protocols'),
('K1310', 'Knowledge of process hazard analysis (PHA) assessments'),
('K1311', 'Knowledge of system assets and boundaries');
