INSERT INTO knowledge_items (code, description) VALUES
('K1059', 'Knowledge of request for information processes'),
('K1063', 'Knowledge of operation assessment processes'),
('K1064', 'Knowledge of Request For Information (RFI) processes'),
('K1065', 'Knowledge of network operations principles and practices'),
('K1066', 'Knowledge of threat behaviors'),
('K1067', 'Knowledge of target behaviors'),
('K1068', 'Knowledge of threat systems and software'),
('K1069', 'Knowledge of virtual machine tools and technologies'),
('K1070', 'Knowledge of privacy disclosure statement laws and regulations'),
('K1071', 'Knowledge of continuous monitoring processes'),
('K1072', 'Knowledge of automated security control testing tools and techniques'),
('K1073', 'Knowledge of hardware asset management principles and practices'),
('K1074', 'Knowledge of software asset management principles and practices'),
('K1076', 'Knowledge of risk scoring principles and practices'),
('K1077', 'Knowledge of data security controls'),
('K1078', 'Knowledge of risk assessment tools and techniques'),
('K1079', 'Knowledge of web application security risks'),
('K1080', 'Knowledge of secure software update principles and practices'),
('K1081', 'Knowledge of secure firmware update principles and practices'),
('K1082', 'Knowledge of ingress filtering tools and techniques'),
('K1083', 'Knowledge of cybersecurity competitions'),
('K1084', 'Knowledge of data privacy controls'),
('K1085', 'Knowledge of exploitation tools and techniques'),
('K1086', 'Knowledge of design modeling'),
('K1087', 'Knowledge of social engineering tools and techniques'),
('K1088', 'Knowledge of knowledge management tools and techniques'),
('K1089', 'Knowledge of protocol analyzer tools and techniques'),
('K1090', 'Knowledge of software, hardware, and peripheral equipment repair tools and techniques'),
('K1091', 'Knowledge of media forensics'),
('K1092', 'Knowledge of digital forensics tools and techniques'),
('K1093', 'Knowledge of black-box software testing'),
('K1094', 'Knowledge of hexadecimal data'),
('K1095', 'Knowledge of design methods'),
('K1096', 'Knowledge of data analysis tools and techniques'),
('K1097', 'Knowledge of data mapping tools and techniques'),
('K1098', 'Knowledge of personnel systems and software'),
('K1099', 'Knowledge of code analysis tools and techniques'),
('K1100', 'Knowledge of analytical tools and techniques'),
('K1101', 'Knowledge of analytics'),
('K1102', 'Knowledge of remote command line tools and techniques'),
('K1103', 'Knowledge of Graphic User Interface (GUI) tools and techniques'),
('K1104', 'Knowledge of geospatial data analysis tools and techniques'),
('K1105', 'Knowledge of non-attributable networks'),
('K1108', 'Knowledge of traceroute tools and techniques'),
('K1109', 'Knowledge of virtual collaborative workspace tools and techniques'),
('K1110', 'Knowledge of acquisition cybersecurity requirements'),
('K1111', 'Knowledge of application security design principles and practices'),
('K1112', 'Knowledge of asset management policies and procedures'),
('K1113', 'Knowledge of blue force tracking'),
('K1114', 'Knowledge of capacity management'),
('K1115', 'Knowledge of Chain of Custody (CoC) processes and procedures'),
('K1116', 'Knowledge of classification guidelines'),
('K1117', 'Knowledge of coding and testing standards'),
('K1118', 'Knowledge of completion criteria'),
('K1119', 'Knowledge of component and interface specifications'),
('K1120', 'Knowledge of Confidentiality, Integrity, Availability, Authenticity, and Non-repudiation (CIAAN) principles and practices'),
('K1121', 'Knowledge of configuration management'),
('K1122', 'Knowledge of configuration management principles and practices'),
('K1123', 'Knowledge of continuous monitoring principles and practices'),
('K1124', 'Knowledge of continuous monitoring scoring and grading metrics'),
('K1125', 'Knowledge of continuous monitoring tools and techniques'),
('K1126', 'Knowledge of cost constraints'),
('K1127', 'Knowledge of customer experience principles and practices'),
('K1128', 'Knowledge of customer requirements'),
('K1129', 'Knowledge of cyber defense auditing laws and regulations'),
('K1130', 'Knowledge of cyber defense auditing policies and practices'),
('K1131', 'Knowledge of cyber defense monitoring tools'),
('K1132', 'Knowledge of cyber defense system analysis tools'),
('K1133', 'Knowledge of cybersecurity engineering'),
('K1135', 'Knowledge of cybersecurity objectives'),
('K1137', 'Knowledge of cybersecurity requirements'),
('K1138', 'Knowledge of cybersecurity standards and best practices'),
('K1140', 'Knowledge of cybersecurity workforce policies and procedures'),
('K1143', 'Knowledge of data classification levels'),
('K1144', 'Knowledge of data correlation tools and techniques'),
('K1145', 'Knowledge of data encryption practices and principles'),
('K1146', 'Knowledge of data gathering tools and techniques'),
('K1147', 'Knowledge of data integrity principles and practices'),
('K1148', 'Knowledge of data manipulation principles and practices'),
('K1149', 'Knowledge of data retrieval principles and practices'),
('K1150', 'Knowledge of data storage principles and practices'),
('K1151', 'Knowledge of digital evidence cataloging tools and techniques'),
('K1152', 'Knowledge of digital evidence extraction tools and techniques'),
('K1153', 'Knowledge of digital evidence handling principles and practices'),
('K1154', 'Knowledge of digital evidence packaging tools and techniques'),
('K1155', 'Knowledge of digital evidence preservation tools and techniques'),
('K1156', 'Knowledge of enterprise cybersecurity architecture'),
('K1157', 'Knowledge of enterprise-wide version control systems'),
('K1158', 'Knowledge of evaluation and validation requirements'),
('K1159', 'Knowledge of fail-over or alternate site requirements'),
('K1160', 'Knowledge of federal and state accreditation standards'),
('K1161', 'Knowledge of financial management'),
('K1163', 'Knowledge of forensic image processing tools and techniques'),
('K1164', 'Knowledge of hardware design principles and practices'),
('K1165', 'Knowledge of independent testing methods'),
('K1166', 'Knowledge of information architecture principles and practices'),
('K1167', 'Knowledge of data sanitization methods'),
('K1168', 'Knowledge of intrusion set tools and techniques'),
('K1169', 'Knowledge of material supportability requirements'),
('K1170', 'Knowledge of mathematical models');
