INSERT INTO knowledge_items (code, description) VALUES
('K0824', 'Knowledge of incident response roles and responsibilities'),
('K0825', 'Knowledge of threat vector characteristics'),
('K0826', 'Knowledge of software security principles and practices'),
('K0827', 'Knowledge of software quality assurance (SQA) principles and practices'),
('K0828', 'Knowledge of supply chain risk management standards and best practices'),
('K0829', 'Knowledge of account creation policies and procedures'),
('K0830', 'Knowledge of password policies and procedures'),
('K0831', 'Knowledge of network attack vectors'),
('K0832', 'Knowledge of cyberattack characteristics'),
('K0833', 'Knowledge of cyberattack actor characteristics'),
('K0834', 'Knowledge of technology procurement principles and practices'),
('K0835', 'Knowledge of risk assessment principles and practices'),
('K0836', 'Knowledge of threat assessment principles and practices'),
('K0837', 'Knowledge of hardening tools and techniques'),
('K0838', 'Knowledge of supply chain risk management policies and procedures'),
('K0839', 'Knowledge of critical infrastructure systems and software'),
('K0840', 'Knowledge of hardware reverse engineering tools and techniques'),
('K0841', 'Knowledge of middleware software capabilities and applications'),
('K0842', 'Knowledge of software reverse engineering tools and techniques'),
('K0844', 'Knowledge of cyberattack stages'),
('K0845', 'Knowledge of cyber intrusion activity phases'),
('K0846', 'Knowledge of secure software deployment principles and practices'),
('K0847', 'Knowledge of secure software deployment tools and techniques'),
('K0848', 'Knowledge of network systems management principles and practices'),
('K0849', 'Knowledge of network systems management tools and techniques'),
('K0850', 'Knowledge of data carving tools and techniques'),
('K0851', 'Knowledge of reverse engineering principles and practices'),
('K0852', 'Knowledge of anti-forensics tools and techniques'),
('K0853', 'Knowledge of forensics lab design principles and practices'),
('K0854', 'Knowledge of forensics lab design systems and software'),
('K0855', 'Knowledge of debugging tools and techniques'),
('K0856', 'Knowledge of filename extension abuse'),
('K0857', 'Knowledge of malware analysis tools and techniques'),
('K0858', 'Knowledge of virtual machine detection tools and techniques'),
('K0859', 'Knowledge of encryption tools and techniques'),
('K0860', 'Knowledge of malware signature principles and practices'),
('K0861', 'Knowledge of network port capabilities and applications'),
('K0862', 'Knowledge of data remediation tools and techniques'),
('K0863', 'Knowledge of cloud computing principles and practices'),
('K0864', 'Knowledge of knowledge management principles and practices'),
('K0865', 'Knowledge of data classification standards and best practices'),
('K0866', 'Knowledge of data classification tools and techniques'),
('K0867', 'Knowledge of database application programming interfaces (APIs)'),
('K0868', 'Knowledge of process improvement principles and practices'),
('K0869', 'Knowledge of process maturity models and frameworks'),
('K0870', 'Knowledge of enterprise architecture (EA) reference models and frameworks'),
('K0871', 'Knowledge of enterprise architecture (EA) principles and practices'),
('K0872', 'Knowledge of service management principles and practices'),
('K0873', 'Knowledge of service management standards and best practices'),
('K0874', 'Knowledge of key management service (KMS) principles and practices'),
('K0875', 'Knowledge of symmetric encryption principles and practices'),
('K0876', 'Knowledge of key management service (KMS) key rotation policies and procedures'),
('K0877', 'Knowledge of application firewall principles and practices'),
('K0878', 'Knowledge of network firewall principles and practices'),
('K0879', 'Knowledge of industry cybersecurity models and frameworks'),
('K0880', 'Knowledge of access control models and frameworks'),
('K0881', 'Knowledge of learning assessment tools and techniques'),
('K0882', 'Knowledge of ethical hacking principles and practices'),
('K0883', 'Knowledge of circuit analysis tools and techniques'),
('K0884', 'Knowledge of covert communication tools and techniques'),
('K0885', 'Knowledge of instructional design principles and practices'),
('K0886', 'Knowledge of instructional design models and frameworks'),
('K0887', 'Knowledge of training policies and procedures'),
('K0888', 'Knowledge of Bloom''s Taxonomy learning levels'),
('K0889', 'Knowledge of learning management system (LMS) systems and software'),
('K0890', 'Knowledge of learning modes'),
('K0891', 'Knowledge of the Open Systems Interconnect (OSI) reference model'),
('K0892', 'Knowledge of cyber defense laws and regulations'),
('K0893', 'Knowledge of training systems and software'),
('K0894', 'Knowledge of computer architecture principles and practices'),
('K0895', 'Knowledge of taxonomy models and frameworks'),
('K0896', 'Knowledge of semantic ontology models and frameworks'),
('K0897', 'Knowledge of logging tools and technologies'),
('K0898', 'Knowledge of cloud service models and frameworks'),
('K0899', 'Knowledge of crisis management protocols'),
('K0900', 'Knowledge of crisis management processes'),
('K0901', 'Knowledge of crisis management tools and techniques'),
('K0902', 'Knowledge of the NIST Workforce Framework for Cybersecurity (NICE Framework)'),
('K0903', 'Knowledge of service desk principles and practices'),
('K0904', 'Knowledge of machine learning principles and practices'),
('K0905', 'Knowledge of media production tool and techniques'),
('K0906', 'Knowledge of multi-level security (MLS) systems and software'),
('K0907', 'Knowledge of cross-domain solutions'),
('K0908', 'Knowledge of human resources policies and procedures'),
('K0909', 'Knowledge of abnormal physical and physiological behaviors'),
('K0910', 'Knowledge of needs assessment principles and practices'),
('K0911', 'Knowledge of remote access tools and techniques'),
('K0912', 'Knowledge of sustainment principles and practices'),
('K0913', 'Knowledge of sustainment processes'),
('K0914', 'Knowledge of binary analysis tools and techniques'),
('K0915', 'Knowledge of network architecture principles and practices'),
('K0916', 'Knowledge of malware analysis principles and practices'),
('K0917', 'Knowledge of Personally Identifiable Information (PII) data security standards and best practices'),
('K0918', 'Knowledge of Payment Card Industry (PCI) data security standards and best practices'),
('K0919', 'Knowledge of Personal Health Information (PHI) data security standards and best practices'),
('K0920', 'Knowledge of risk management policies and procedures'),
('K0921', 'Knowledge of program protection plan (PPP) principles and practices'),
('K0922', 'Knowledge of the acquisition life cycle models and frameworks'),
('K0923', 'Knowledge of operating system structures and internals'),
('K0924', 'Knowledge of network analysis tools and techniques');
