INSERT INTO knowledge_items (code, description) VALUES
('K0724', 'Knowledge of incident response principles and practices'),
('K0725', 'Knowledge of incident response tools and techniques'),
('K0726', 'Knowledge of incident handling tools and techniques'),
('K0727', 'Knowledge of analysis standards and best practices'),
('K0728', 'Knowledge of Confidentiality, Integrity and Availability (CIA) principles and practices'),
('K0729', 'Knowledge of non-repudiation principles and practices'),
('K0730', 'Knowledge of cyber safety principles and practices'),
('K0731', 'Knowledge of systems security engineering (SSE) principles and practices'),
('K0732', 'Knowledge of intrusion detection tools and techniques'),
('K0733', 'Knowledge of information technology (IT) architecture models and frameworks'),
('K0734', 'Knowledge of Risk Management Framework (RMF) requirements'),
('K0735', 'Knowledge of risk management models and frameworks'),
('K0736', 'Knowledge of information technology (IT) security principles and practices'),
('K0737', 'Knowledge of bandwidth management tools and techniques'),
('K0738', 'Knowledge of low-level programming languages'),
('K0739', 'Knowledge of mathematics principles and practices'),
('K0740', 'Knowledge of system performance indicators'),
('K0741', 'Knowledge of system availability measures'),
('K0742', 'Knowledge of identity and access management (IAM) principles and practices'),
('K0743', 'Knowledge of new and emerging technologies'),
('K0744', 'Knowledge of operating system (OS) systems and software'),
('K0745', 'Knowledge of parallel and distributed computing principles and practices'),
('K0746', 'Knowledge of policy-based access controls'),
('K0747', 'Knowledge of Risk Adaptive (Adaptable) Access Controls (RAdAC)'),
('K0748', 'Knowledge of Privacy Impact Assessment (PIA) principles and practices'),
('K0749', 'Knowledge of process engineering principles and practices'),
('K0750', 'Knowledge of query languages'),
('K0751', 'Knowledge of system threats'),
('K0752', 'Knowledge of system vulnerabilities'),
('K0753', 'Knowledge of remote access principles and practices'),
('K0754', 'Knowledge of resource management principles and practices'),
('K0755', 'Knowledge of configuration management (CM) tools and techniques'),
('K0756', 'Knowledge of security management principles and practices'),
('K0757', 'Knowledge of system design tools and techniques'),
('K0758', 'Knowledge of server administration principles and practices'),
('K0759', 'Knowledge of client and server architecture'),
('K0760', 'Knowledge of server diagnostic tools and techniques'),
('K0761', 'Knowledge of Fault Detection and Diagnostics (FDD) tools and techniques'),
('K0762', 'Knowledge of software debugging principles and practices'),
('K0763', 'Knowledge of software design tools and techniques'),
('K0764', 'Knowledge of software development models and frameworks'),
('K0765', 'Knowledge of software engineering principles and practices'),
('K0766', 'Knowledge of data asset management principles and practices'),
('K0767', 'Knowledge of structured analysis principles and practices'),
('K0768', 'Knowledge of automated systems analysis tools and techniques'),
('K0769', 'Knowledge of system design standards and best practices'),
('K0770', 'Knowledge of system administration principles and practices'),
('K0771', 'Knowledge of system life cycle management principles and practices'),
('K0772', 'Knowledge of systems testing and evaluation tools and techniques'),
('K0773', 'Knowledge of telecommunications principles and practices'),
('K0774', 'Knowledge of content creation tools and techniques'),
('K0775', 'Knowledge of information management tools and techniques'),
('K0776', 'Knowledge of collaboration tools and techniques'),
('K0777', 'Knowledge of data storage media characteristics'),
('K0778', 'Knowledge of enterprise information technology (IT) architecture principles and practices'),
('K0779', 'Knowledge of systems engineering processes'),
('K0780', 'Knowledge of hardware maintenance policies and procedures'),
('K0781', 'Knowledge of virtual private network (VPN) systems and software'),
('K0782', 'Knowledge of web service protocols'),
('K0783', 'Knowledge of network attack characteristics'),
('K0784', 'Knowledge of insider threat laws and regulations'),
('K0785', 'Knowledge of insider threat tools and techniques'),
('K0786', 'Knowledge of physical computer components'),
('K0787', 'Knowledge of computer peripherals'),
('K0788', 'Knowledge of adversarial tactics principles and practices'),
('K0789', 'Knowledge of adversarial tactics tools and techniques'),
('K0790', 'Knowledge of adversarial tactics policies and procedures'),
('K0791', 'Knowledge of defense-in-depth principles and practices'),
('K0792', 'Knowledge of network configurations'),
('K0793', 'Knowledge of file extensions'),
('K0794', 'Knowledge of file system implementation principles and practices'),
('K0795', 'Knowledge of digital evidence seizure policies and procedures'),
('K0796', 'Knowledge of digital evidence preservation policies and procedures'),
('K0797', 'Knowledge of ethical hacking tools and techniques'),
('K0798', 'Knowledge of program management principles and practices'),
('K0799', 'Knowledge of project management principles and practices'),
('K0800', 'Knowledge of evidence admissibility laws and regulations'),
('K0801', 'Knowledge of cognitive domain models and frameworks'),
('K0802', 'Knowledge of chain of custody policies and procedures'),
('K0803', 'Knowledge of supply chain risk management principles and practices'),
('K0804', 'Knowledge of persistent data principles and practices'),
('K0805', 'Knowledge of command-line tools and techniques'),
('K0806', 'Knowledge of machine virtualization tools and techniques'),
('K0807', 'Knowledge of web mail tools and techniques'),
('K0808', 'Knowledge of system file characteristics'),
('K0809', 'Knowledge of digital forensics data characteristics'),
('K0810', 'Knowledge of deployable forensics principles and practices'),
('K0811', 'Knowledge of web filtering systems and software'),
('K0812', 'Knowledge of digital communication systems and software'),
('K0813', 'Knowledge of interpreted and compiled programming language characteristics'),
('K0814', 'Knowledge of secure coding tools and techniques'),
('K0815', 'Knowledge of intelligence collection management processes'),
('K0816', 'Knowledge of front-end intelligence collection systems and software'),
('K0817', 'Knowledge of event correlation tools and techniques'),
('K0818', 'Knowledge of new and emerging cybersecurity risks'),
('K0819', 'Knowledge of import and export control laws and regulations'),
('K0820', 'Knowledge of supply chain risks'),
('K0821', 'Knowledge of federal agency roles and responsibilities'),
('K0822', 'Knowledge of risk tolerance principles and practices'),
('K0823', 'Knowledge of incident response policies and procedures');
