INSERT INTO knowledge_items (code, description) VALUES
('K0925', 'Knowledge of wireless communication tools and techniques'),
('K0926', 'Knowledge of signal jamming tools and techniques'),
('K0927', 'Knowledge of configuration management tools and techniques'),
('K0928', 'Knowledge of systems engineering principles and practices'),
('K0929', 'Knowledge of content synchronization tools and techniques'),
('K0930', 'Knowledge of credential management systems and software'),
('K0931', 'Knowledge of data-at-rest encryption (DARE) standards and best practices'),
('K0932', 'Knowledge of cryptographic key storage systems and software'),
('K0933', 'Knowledge of N-tier architecture principles and practices'),
('K0934', 'Knowledge of data classification policies and procedures'),
('K0935', 'Knowledge of incident, event, and problem management policies and procedures'),
('K0936', 'Knowledge of network hardware threats and vulnerabilities'),
('K0937', 'Knowledge of countermeasure design principles and practices'),
('K0938', 'Knowledge of network mapping principles and practices'),
('K0939', 'Knowledge of packet-level analysis tools and techniques'),
('K0940', 'Knowledge of subnet tools and techniques'),
('K0941', 'Knowledge of data concealment tools and techniques'),
('K0942', 'Knowledge of cryptology principles and practices'),
('K0943', 'Knowledge of industry indicators'),
('K0944', 'Knowledge of intelligence data gathering principles and practices'),
('K0945', 'Knowledge of intelligence data gathering policies and procedures'),
('K0946', 'Knowledge of incident reporting policies and procedures'),
('K0947', 'Knowledge of computer engineering principles and practices'),
('K0948', 'Knowledge of embedded systems and software'),
('K0949', 'Knowledge of fault tolerance tools and techniques'),
('K0950', 'Knowledge of Intrusion Detection System (IDS) tools and techniques'),
('K0951', 'Knowledge of Intrusion Prevention System (IPS) tools and techniques'),
('K0952', 'Knowledge of information theory principles and practices'),
('K0953', 'Knowledge of data mining tools and techniques'),
('K0954', 'Knowledge of foreign disclosure policies and procedures'),
('K0955', 'Knowledge of penetration testing principles and practices'),
('K0956', 'Knowledge of penetration testing tools and techniques'),
('K0957', 'Knowledge of root cause analysis tools and techniques'),
('K0958', 'Knowledge of system integration principles and practices'),
('K0959', 'Knowledge of operational design principles and practices'),
('K0960', 'Knowledge of content management system (CMS) capabilities and applications'),
('K0961', 'Knowledge of planning systems and software'),
('K0962', 'Knowledge of targeting laws and regulations'),
('K0963', 'Knowledge of exploitation laws and regulations'),
('K0965', 'Knowledge of language analysis tools and techniques'),
('K0966', 'Knowledge of voice analysis tools and techniques'),
('K0967', 'Knowledge of graphic materials analysis tools and techniques'),
('K0968', 'Knowledge of analytic standards and frameworks'),
('K0969', 'Knowledge of cyberattack tools and techniques'),
('K0970', 'Knowledge of auditing policies and procedures'),
('K0971', 'Knowledge of logging policies and procedures'),
('K0973', 'Knowledge of system persistence tools and techniques'),
('K0977', 'Knowledge of intelligence collection management tools and techniques'),
('K0979', 'Knowledge of information searching tools and techniques'),
('K0980', 'Knowledge of intelligence collection sources'),
('K0983', 'Knowledge of computer networking principles and practices'),
('K0984', 'Knowledge of web security principles and practices'),
('K0986', 'Knowledge of target selection criticality factors'),
('K0987', 'Knowledge of target selection vulnerability factors'),
('K0988', 'Knowledge of active defense tools and techniques'),
('K0989', 'Knowledge of intelligence information repositories'),
('K0990', 'Knowledge of cyber operations principles and practices'),
('K0991', 'Knowledge of database administration principles and practices'),
('K0992', 'Knowledge of database maintenance principles and practices'),
('K0993', 'Knowledge of deconfliction processes'),
('K0994', 'Knowledge of denial and deception tools and techniques'),
('K0998', 'Knowledge of Wireless Local Area Network (WLAN) tools and techniques'),
('K0999', 'Knowledge of information management principles and practices'),
('K1000', 'Knowledge of evasion principles and practices'),
('K1001', 'Knowledge of evasion tools and techniques'),
('K1002', 'Knowledge of supervisory control and data acquisition (SCADA) systems and software'),
('K1004', 'Knowledge of reporting policies and procedures'),
('K1005', 'Knowledge of intelligence collection capabilities and applications'),
('K1007', 'Knowledge of intelligence requirements tasking systems and software'),
('K1008', 'Knowledge of intelligence support activities'),
('K1009', 'Knowledge of threat intelligence principles and practices'),
('K1010', 'Knowledge of intelligence policies and procedures'),
('K1011', 'Knowledge of network addressing principles and practices'),
('K1012', 'Knowledge of malware characteristics'),
('K1014', 'Knowledge of network security principles and practices'),
('K1015', 'Knowledge of network topology principles and practices'),
('K1016', 'Knowledge of code obfuscation tools and techniques'),
('K1017', 'Knowledge of operational effectiveness assessment principles and practices'),
('K1019', 'Knowledge of operations security (OPSEC) principles and practices'),
('K1020', 'Knowledge of organization decision support tools and techniques'),
('K1021', 'Knowledge of resource and asset readiness reporting policies and procedures'),
('K1023', 'Knowledge of network exploitation tools and techniques'),
('K1024', 'Knowledge of partnership policies and procedures'),
('K1025', 'Knowledge of decision-making policies and procedures'),
('K1026', 'Knowledge of requirements submission processes'),
('K1027', 'Knowledge of post implementation review (PIR) processes'),
('K1028', 'Knowledge of target development principles and practices'),
('K1030', 'Knowledge of operational planning tools and techniques'),
('K1031', 'Knowledge of risk mitigation tools and techniques'),
('K1032', 'Knowledge of satellite-based communication systems and software'),
('K1033', 'Knowledge of scripting principles and practices'),
('K1034', 'Knowledge of target language'),
('K1035', 'Knowledge of target research tools and techniques'),
('K1045', 'Knowledge of tasking processes'),
('K1049', 'Knowledge of routing protocols'),
('K1050', 'Knowledge of critical information requirements'),
('K1051', 'Knowledge of collection data flow from origin into repositories and tools'),
('K1054', 'Knowledge of red team functions and capabilities'),
('K1055', 'Knowledge of digital forensics principles and practices'),
('K1056', 'Knowledge of language analysis principles and practices');
