INSERT INTO knowledge_items (code, description) VALUES
('K0018', 'Knowledge of encryption algorithms'),
('K0055', 'Knowledge of microprocessors'),
('K0064', 'Knowledge of performance tuning tools and techniques'),
('K0068', 'Knowledge of programming language structures and logic'),
('K0092', 'Knowledge of technology integration processes'),
('K0159', 'Knowledge of Voice over IP (VoIP)'),
('K0176', 'Knowledge of Extensible Markup Language (XML) schemas'),
('K0375', 'Knowledge of wireless applications vulnerabilities'),
('K0470', 'Knowledge of Internet and routing protocols'),
('K0476', 'Knowledge of language processing tools and techniques'),
('K0480', 'Knowledge of malware'),
('K0498', 'Knowledge of operational planning processes'),
('K0635', 'Knowledge of decryption'),
('K0636', 'Knowledge of decryption tools and techniques'),
('K0637', 'Knowledge of data repositories'),
('K0638', 'Knowledge of security awareness programs'),
('K0639', 'Knowledge of code tailoring tools and techniques'),
('K0640', 'Knowledge of the organizational cybersecurity workforce'),
('K0641', 'Knowledge of market research tools and techniques'),
('K0642', 'Knowledge of pricing structures'),
('K0643', 'Knowledge of virtual learning environments'),
('K0644', 'Knowledge of cybersecurity operation policies and procedures'),
('K0645', 'Knowledge of standard operating procedures (SOPs)'),
('K0646', 'Knowledge of system optimization techniques'),
('K0647', 'Knowledge of data visualization tools and techniques'),
('K0648', 'Knowledge of career paths'),
('K0649', 'Knowledge of organizational career progressions'),
('K0650', 'Knowledge of supplier assessment criteria'),
('K0651', 'Knowledge of trustworthiness principles'),
('K0652', 'Knowledge of workforce trends'),
('K0653', 'Knowledge of cybersecurity practices in the acquisition process'),
('K0654', 'Knowledge of target audience requirements'),
('K0655', 'Knowledge of intelligence fusion'),
('K0656', 'Knowledge of network collection tools and techniques'),
('K0657', 'Knowledge of network collection policies and procedures'),
('K0658', 'Knowledge of cognitive biases'),
('K0659', 'Knowledge of information privacy technologies'),
('K0660', 'Knowledge of appropriate use policies and procedures'),
('K0661', 'Knowledge of reauthorization processes'),
('K0662', 'Knowledge of systems security engineering'),
('K0663', 'Knowledge of industry standards and best practices'),
('K0664', 'Knowledge of stakeholder management'),
('K0666', 'Knowledge of system security plans'),
('K0667', 'Knowledge of contracts'),
('K0668', 'Knowledge of contract management'),
('K0669', 'Knowledge of contractor management'),
('K0670', 'Knowledge of life cycle development milestones'),
('K0671', 'Knowledge of Communications Security (COMSEC) policies and procedures'),
('K0672', 'Knowledge of the Communications Security (COMSEC) Material Control System (CMCS)'),
('K0673', 'Knowledge of types of Communications Security (COMSEC) incidents'),
('K0674', 'Knowledge of computer networking protocols'),
('K0675', 'Knowledge of risk management processes'),
('K0676', 'Knowledge of cybersecurity laws and regulations'),
('K0677', 'Knowledge of cybersecurity policies and procedures'),
('K0678', 'Knowledge of privacy laws and regulations'),
('K0679', 'Knowledge of privacy policies and procedures'),
('K0680', 'Knowledge of cybersecurity principles and practices'),
('K0681', 'Knowledge of privacy principles and practices'),
('K0682', 'Knowledge of cybersecurity threats'),
('K0683', 'Knowledge of cybersecurity vulnerabilities'),
('K0684', 'Knowledge of cybersecurity threat characteristics'),
('K0685', 'Knowledge of access control principles and practices'),
('K0686', 'Knowledge of authentication and authorization tools and techniques'),
('K0687', 'Knowledge of business operations standards and best practices'),
('K0688', 'Knowledge of common application vulnerabilities'),
('K0689', 'Knowledge of network infrastructure principles and practices'),
('K0690', 'Knowledge of requirements analysis principles and practices'),
('K0691', 'Knowledge of cyber defense tools and techniques'),
('K0692', 'Knowledge of vulnerability assessment tools and techniques'),
('K0693', 'Knowledge of complex data structure capabilities and applications'),
('K0694', 'Knowledge of computer algorithm capabilities and applications'),
('K0695', 'Knowledge of programming principles and practices'),
('K0696', 'Knowledge of digital forensic data principles and practices'),
('K0697', 'Knowledge of encryption algorithm capabilities and applications'),
('K0698', 'Knowledge of cryptographic key management principles and practices'),
('K0699', 'Knowledge of data administration policies and procedures'),
('K0700', 'Knowledge of data standardization policies and procedures'),
('K0701', 'Knowledge of data backup and recovery policies and procedures'),
('K0702', 'Knowledge of data warehousing principles and practices'),
('K0703', 'Knowledge of data mining principles and practices'),
('K0704', 'Knowledge of database management system (DBMS) principles and practices'),
('K0705', 'Knowledge of database query language capabilities and applications'),
('K0706', 'Knowledge of database schema capabilities and applications'),
('K0707', 'Knowledge of database systems and software'),
('K0708', 'Knowledge of digital rights management (DRM) tools and techniques'),
('K0709', 'Knowledge of business continuity and disaster recovery (BCDR) policies and procedures'),
('K0710', 'Knowledge of enterprise cybersecurity architecture principles and practices'),
('K0711', 'Knowledge of evaluation and validation principles and practices'),
('K0712', 'Knowledge of Local Area Networks (LAN)'),
('K0713', 'Knowledge of Wide Area Networks (WAN)'),
('K0714', 'Knowledge of electrical engineering principles and practices'),
('K0715', 'Knowledge of resiliency and redundancy principles and practices'),
('K0716', 'Knowledge of host access control (HAC) systems and software'),
('K0717', 'Knowledge of network access control (NAC) systems and software'),
('K0718', 'Knowledge of network communications principles and practices'),
('K0719', 'Knowledge of human-computer interaction (HCI) principles and practices'),
('K0720', 'Knowledge of Security Assessment and Authorization (SA&A) processes'),
('K0721', 'Knowledge of risk management principles and practices'),
('K0722', 'Knowledge of software development principles and practices'),
('K0723', 'Knowledge of vulnerability data sources');
