INSERT INTO skills (code, description) VALUES
('S0569', 'Skill in designing security controls'),
('S0570', 'Skill in designing the integration of hardware solutions'),
('S0571', 'Skill in designing the integration of software solutions'),
('S0572', 'Skill in detecting host- and network-based intrusions'),
('S0573', 'Skill in developing testing scenarios'),
('S0574', 'Skill in developing security system controls'),
('S0575', 'Skill in developing network infrastructure contingency and recovery plans'),
('S0576', 'Skill in testing network infrastructure contingency and recovery plans'),
('S0577', 'Skill in troubleshooting computer networks'),
('S0578', 'Skill in evaluating security designs'),
('S0579', 'Skill in preparing reports'),
('S0580', 'Skill in monitoring system performance'),
('S0581', 'Skill in configuring systems for performance enhancement'),
('S0582', 'Skill in troubleshooting system performance'),
('S0583', 'Skill in implementing established network security practices'),
('S0584', 'Skill in configuring network devices'),
('S0585', 'Skill in installing network devices'),
('S0586', 'Skill in administering databases'),
('S0587', 'Skill in maintaining directory services'),
('S0588', 'Skill in performing threat modeling'),
('S0589', 'Skill in preserving digital evidence integrity'),
('S0590', 'Skill in building use cases'),
('S0591', 'Skill in performing social engineering'),
('S0592', 'Skill in tuning network sensors'),
('S0593', 'Skill in handling incidents'),
('S0594', 'Skill in repairing hardware'),
('S0595', 'Skill in repairing system peripherals'),
('S0596', 'Skill in encrypting network communications'),
('S0597', 'Skill in writing code in a currently supported programming language'),
('S0598', 'Skill in creating test plans'),
('S0599', 'Skill in performing memory dump analysis'),
('S0600', 'Skill in collecting relevant data from a variety of sources'),
('S0601', 'Skill in developing curricula'),
('S0602', 'Skill in teaching training programs'),
('S0603', 'Skill in identifying forensics data in diverse media'),
('S0604', 'Skill in extracting forensics data in diverse media'),
('S0605', 'Skill in storing digital evidence'),
('S0606', 'Skill in manipulating operating system components'),
('S0607', 'Skill in collecting digital evidence'),
('S0608', 'Skill in processing digital evidence'),
('S0609', 'Skill in transporting digital evidence'),
('S0610', 'Skill in communicating effectively'),
('S0611', 'Skill in disassembling Personal Computers (PCs)'),
('S0612', 'Skill in performing digital forensics analysis'),
('S0613', 'Skill in configuring software-based computer protection tools'),
('S0614', 'Skill in categorizing types of vulnerabilities'),
('S0615', 'Skill in protecting a network against malware'),
('S0616', 'Skill in applying black-box software testing'),
('S0617', 'Skill in interpreting signatures'),
('S0618', 'Skill in configuring network protection components'),
('S0619', 'Skill in auditing technical systems'),
('S0620', 'Skill in evaluating the trustworthiness of a supply chain'),
('S0621', 'Skill in performing binary analysis'),
('S0622', 'Skill in implementing one-way hash functions'),
('S0623', 'Skill in performing source code analysis'),
('S0624', 'Skill in performing volatile data analysis'),
('S0625', 'Skill in interpreting debugger results'),
('S0626', 'Skill in identifying common encoding techniques'),
('S0627', 'Skill in reading signatures'),
('S0628', 'Skill in developing learning activities'),
('S0629', 'Skill in applying technologies for instructional purposes'),
('S0630', 'Skill in conducting Test Readiness Reviews (TRR)'),
('S0631', 'Skill in performing data preprocessing'),
('S0632', 'Skill in designing Test and Evaluation Strategies (TES)'),
('S0633', 'Skill in developing position qualification requirements'),
('S0634', 'Skill in identifying Test and Evaluation Strategies (TES) infrastructure requirements'),
('S0635', 'Skill in managing test assets'),
('S0636', 'Skill in performing format conversions'),
('S0637', 'Skill in designing multi-level security solutions'),
('S0638', 'Skill in designing cross-domain solutions'),
('S0639', 'Skill in providing test and evaluation resource estimates'),
('S0640', 'Skill in performing regression analysis'),
('S0641', 'Skill in reviewing logs'),
('S0642', 'Skill in identifying evidence of past intrusions'),
('S0643', 'Skill in applying hardening techniques'),
('S0644', 'Skill in performing transformation analytics'),
('S0645', 'Skill in troubleshooting cyber defense infrastructure anomalies'),
('S0646', 'Skill in applying descriptive statistics'),
('S0647', 'Skill in managing a workforce'),
('S0648', 'Skill in detecting anomalies'),
('S0649', 'Skill in removing outliers'),
('S0650', 'Skill in writing scripts'),
('S0651', 'Skill in performing malware analysis'),
('S0652', 'Skill in performing bit-level analysis'),
('S0653', 'Skill in creating digital evidence copies'),
('S0654', 'Skill in conducting system reviews'),
('S0655', 'Skill in designing secure test plans'),
('S0656', 'Skill in assessing application vulnerabilities'),
('S0657', 'Skill in implementing Public Key Infrastructure (PKI) encryption'),
('S0658', 'Skill in implementing digital signatures'),
('S0659', 'Skill in applying security models'),
('S0660', 'Skill in performing systems engineering'),
('S0661', 'Skill in troubleshooting client-level problems'),
('S0662', 'Skill in managing servers'),
('S0663', 'Skill in managing workstations'),
('S0664', 'Skill in applying policies that meet system security objectives'),
('S0665', 'Skill in creating policies'),
('S0666', 'Skill in defining performance objectives'),
('S0667', 'Skill in assessing security controls'),
('S0668', 'Skill in designing technology processes and solutions');
