INSERT INTO skills (code, description) VALUES
('S0669', 'Skill in integrating technology processes and solutions'),
('S0670', 'Skill in implementing error handling in applications'),
('S0671', 'Skill in implementing network infrastructure contingency and recovery plans'),
('S0672', 'Skill in troubleshooting failed system components'),
('S0673', 'Skill in translating operational requirements into security controls'),
('S0674', 'Skill in installing system and component upgrades'),
('S0675', 'Skill in optimizing system performance'),
('S0677', 'Skill in recovering failed systems'),
('S0678', 'Skill in administering operating systems'),
('S0679', 'Skill in configuring network workstations and peripherals'),
('S0680', 'Skill in validating network workstations and peripherals'),
('S0681', 'Skill in performing design modeling'),
('S0682', 'Skill in applying subnet techniques'),
('S0683', 'Skill in implementing network segregation'),
('S0685', 'Skill in configuring computer protection components'),
('S0686', 'Skill in performing risk assessments'),
('S0687', 'Skill in performing administrative planning activities'),
('S0688', 'Skill in performing network data analysis'),
('S0690', 'Skill in performing midpoint collection data analysis'),
('S0694', 'Skill in auditing network devices'),
('S0695', 'Skill in performing Open Source Intelligence (OSINT) research'),
('S0696', 'Skill in conducting deep web research'),
('S0700', 'Skill in mining data'),
('S0701', 'Skill in performing data mining analysis'),
('S0702', 'Skill in defining an operational environment'),
('S0703', 'Skill in depicting data on a network map'),
('S0704', 'Skill in performing target analysis'),
('S0705', 'Skill in installing patches'),
('S0706', 'Skill in identifying patch signatures'),
('S0707', 'Skill in developing comprehensive cyber operations assessment programs'),
('S0708', 'Skill in executing comprehensive cyber operations assessment programs'),
('S0709', 'Skill in developing analytics'),
('S0710', 'Skill in evaluating metadata'),
('S0711', 'Skill in interpreting metadata'),
('S0712', 'Skill in evaluating data source quality'),
('S0713', 'Skill in evaluating information quality'),
('S0715', 'Skill in generating operation plans'),
('S0718', 'Skill in identifying cybersecurity threats'),
('S0719', 'Skill in identifying intelligence gaps'),
('S0720', 'Skill in identifying regional languages and dialects'),
('S0721', 'Skill in prioritizing information'),
('S0722', 'Skill in interpreting traceroute results'),
('S0723', 'Skill in interpreting vulnerability scanner results'),
('S0724', 'Skill in managing client relationships'),
('S0725', 'Skill in performing network visualization'),
('S0726', 'Skill in performing data normalization'),
('S0727', 'Skill in performing data fusion'),
('S0728', 'Skill in preparing briefings'),
('S0729', 'Skill in preparing plans'),
('S0731', 'Skill in producing after-action reports'),
('S0732', 'Skill in recognizing malicious network activity in traffic'),
('S0733', 'Skill in interpreting malicious network activity in traffic'),
('S0734', 'Skill in identifying technical information'),
('S0735', 'Skill in programming'),
('S0736', 'Skill in researching software vulnerabilities'),
('S0737', 'Skill in researching software exploits'),
('S0738', 'Skill in performing reverse engineering of software'),
('S0739', 'Skill in analyzing intelligence products'),
('S0741', 'Skill in administering servers'),
('S0743', 'Skill in identifying network anomalies'),
('S0744', 'Skill in performing technical writing'),
('S0745', 'Skill in testing tools for implementation'),
('S0746', 'Skill in evaluating tools for implementation'),
('S0748', 'Skill in querying data'),
('S0749', 'Skill in determining relevant information'),
('S0751', 'Skill in conducting open-source searches'),
('S0752', 'Skill in evading network detection'),
('S0754', 'Skill in establishing persistence'),
('S0755', 'Skill in reconstructing a network'),
('S0756', 'Skill in incorporating feedback'),
('S0757', 'Skill in verifying the integrity of files'),
('S0758', 'Skill in performing wireless network analysis'),
('S0759', 'Skill in identifying requirements'),
('S0760', 'Skill in navigating databases'),
('S0761', 'Skill in performing strategic guidance analysis'),
('S0762', 'Skill in integrating organization objectives'),
('S0764', 'Skill in comparing indicators with requirements'),
('S0765', 'Skill in converting intelligence requirements into intelligence production tasks'),
('S0766', 'Skill in coordinating product development'),
('S0768', 'Skill in allocating resources'),
('S0769', 'Skill in defining progress indicators'),
('S0770', 'Skill in defining success indicators'),
('S0771', 'Skill in creating planning documents'),
('S0772', 'Skill in maintaining planning documents'),
('S0773', 'Skill in tracking services'),
('S0775', 'Skill in developing intelligence collection plans'),
('S0777', 'Skill in developing collection strategies'),
('S0779', 'Skill in determining information requirements'),
('S0780', 'Skill in fulfilling information requests'),
('S0782', 'Skill in determining capability estimates'),
('S0783', 'Skill in creating decision support materials'),
('S0784', 'Skill in implementing established procedures'),
('S0785', 'Skill in interpreting planning guidance'),
('S0786', 'Skill in interpreting readiness reporting'),
('S0788', 'Skill in orchestrating planning teams'),
('S0789', 'Skill in coordinating collection support'),
('S0790', 'Skill in monitoring status'),
('S0791', 'Skill in presenting to an audience'),
('S0793', 'Skill in analyzing performance specifications'),
('S0794', 'Skill in establishing timelines');
