INSERT INTO skills (code, description) VALUES
('S0796', 'Skill in creating privacy policies'),
('S0797', 'Skill in negotiating vendor agreements'),
('S0798', 'Skill in evaluating vendor privacy practices'),
('S0799', 'Skill in anticipating new security threats'),
('S0800', 'Skill in analyzing organizational patterns and relationships'),
('S0801', 'Skill in assessing partner operations capabilities'),
('S0804', 'Skill in assessing an organization''s threat environment'),
('S0805', 'Skill in designing incident responses'),
('S0806', 'Skill in performing incident responses'),
('S0807', 'Skill in solving problems'),
('S0808', 'Skill in assessing an organization’s data assets'),
('S0809', 'Skill in utilizing cyber defense service provider information'),
('S0810', 'Skill in responding to threat reports'),
('S0811', 'Skill in managing intelligence collection requirements'),
('S0812', 'Skill in performing supply chain analysis'),
('S0813', 'Skill in identifying cybersecurity issues in external connections'),
('S0814', 'Skill in identifying privacy issues in partner interconnections'),
('S0815', 'Skill in troubleshooting network equipment'),
('S0816', 'Skill in developing curriculum standards'),
('S0817', 'Skill in building internal and external relationships'),
('S0818', 'Skill in building internal and external stakeholder relationships'),
('S0819', 'Skill in caching data'),
('S0820', 'Skill in cataloging data'),
('S0821', 'Skill in collaborating with internal and external stakeholders'),
('S0822', 'Skill in collaborating with stakeholders'),
('S0824', 'Skill in communicating with customers'),
('S0825', 'Skill in communicating with engineering staff'),
('S0826', 'Skill in communicating with external organizations'),
('S0827', 'Skill in communicating with internal and external stakeholders'),
('S0828', 'Skill in compiling data'),
('S0829', 'Skill in conducting customer interviews'),
('S0830', 'Skill in conducting feasibility studies'),
('S0831', 'Skill in configuring hardware'),
('S0832', 'Skill in cooperating with internal and external stakeholders'),
('S0833', 'Skill in correlating incident data'),
('S0834', 'Skill in developing technical reports'),
('S0835', 'Skill in distributing data'),
('S0836', 'Skill in encrypting data'),
('S0837', 'Skill in executing computer scripts to automate tasks'),
('S0838', 'Skill in identifying anomalous activities'),
('S0839', 'Skill in identifying exploited system weaknesses'),
('S0840', 'Skill in identifying misuse activities'),
('S0841', 'Skill in identifying possible security violations'),
('S0842', 'Skill in interpreting test results'),
('S0843', 'Skill in maintaining data'),
('S0844', 'Skill in managing account access rights'),
('S0845', 'Skill in mapping networks'),
('S0846', 'Skill in monitoring system activity'),
('S0848', 'Skill in performing behavioral analysis'),
('S0850', 'Skill in performing cost/benefit analysis'),
('S0852', 'Skill in performing cyber defense trend analysis'),
('S0853', 'Skill in performing cybersecurity architecture analysis'),
('S0854', 'Skill in performing data analysis'),
('S0855', 'Skill in performing data requirement analysis'),
('S0856', 'Skill in performing digital evidence analysis'),
('S0857', 'Skill in performing dynamic analysis'),
('S0858', 'Skill in performing economic analysis'),
('S0859', 'Skill in performing event correlation'),
('S0860', 'Skill in performing file system forensic analysis'),
('S0861', 'Skill in performing gap analysis'),
('S0862', 'Skill in performing geospatial analysis'),
('S0863', 'Skill in performing incident analysis'),
('S0866', 'Skill in performing log file analysis'),
('S0867', 'Skill in performing malicious activity analysis'),
('S0868', 'Skill in performing market analysis'),
('S0869', 'Skill in performing metadata analysis'),
('S0870', 'Skill in performing needs analysis'),
('S0871', 'Skill in performing network analysis'),
('S0872', 'Skill in performing network data flow analysis'),
('S0874', 'Skill in performing network traffic analysis'),
('S0875', 'Skill in performing network traffic packet analysis'),
('S0876', 'Skill in performing nodal analysis'),
('S0877', 'Skill in performing quantitative analysis'),
('S0878', 'Skill in performing risk analysis'),
('S0879', 'Skill in performing scientific analysis'),
('S0880', 'Skill in performing security architecture analysis'),
('S0882', 'Skill in performing static analysis'),
('S0883', 'Skill in performing static code analysis'),
('S0884', 'Skill in performing static malware analysis'),
('S0885', 'Skill in performing system activity analysis'),
('S0886', 'Skill in performing system analysis'),
('S0889', 'Skill in performing test result analysis'),
('S0890', 'Skill in performing threat analysis'),
('S0891', 'Skill in performing trade-off analysis'),
('S0892', 'Skill in performing trend analysis'),
('S0893', 'Skill in performing user needs analysis'),
('S0896', 'Skill in recognizing behavioral patterns'),
('S0897', 'Skill in retrieving data'),
('S0898', 'Skill in testing hardware'),
('S0899', 'Skill in testing interfaces'),
('S0900', 'Skill in analyzing information from multiple sources'),
('S0902', 'Skill in building relationships remotely and in person'),
('S0904', 'Skill in correlating data from multiple tools'),
('S0905', 'Skill in determining what information may helpful to a specific audience'),
('S0906', 'Skill in identifying insider risk security gaps'),
('S0907', 'Skill in identifying insider threats'),
('S0908', 'Skill in determining the importance of assets'),
('S0909', 'Skill in integrating information from multiple sources'),
('S0910', 'Skill in performing cyberintelligence data analysis'),
('S0911', 'Skill in performing data queries'),
('S0912', 'Skill in performing human behavioral analysis'),
('S0913', 'Skill in performing link analysis'),
('S0916', 'Skill in recognizing recurring threat incidents'),
('S0917', 'Skill in forecasting likely impacts on mission or business functions resulting from adversity'),
('S0918', 'Skill in conducting ongoing monitoring of system properties and behaviors'),
('S0919', 'Skill in evaluating threats, events, and courses of action in the context of mission or business functions'),
('S0920', 'Skill in establishing segmentation of system assets based on criticality and trustworthiness'),
('S0921', 'Skill in performing telemetry analysis'),
('S0922', 'Skill in making decisions under conditions of uncertainty'),
('S0923', 'Skill in communicating at varying levels of technical detail with stakeholders of various backgrounds'),
('S0924', 'Skill in crisis management'),
('S0925', 'Skill in developing and analyzing attack paths'),
('S0926', 'Skill in designing and maintaining threat catalogs'),
('S0927', 'Skill in defining contingency plans'),
('S0928', 'Skill in defining loss scenarios'),
('S0929', 'Skill in designing air-gapped data vault solutions'),
('S0930', 'Skill in defining impact tolerance statements '),
('S0931', 'Skill in conducting technical business impact analysis'),
('S0932', 'Skill in protecting critical assets'),
('S0933', 'Skill in designing enhanced controls for critical assets'),
('S0934', 'Skill in performing Fault Tree Analysis (FTA)'),
('S0935', 'Skill in live acquisition'),
('S0936', 'Skill in deadbox acquisition'),
('S0937', 'Skill in inspecting data for ingestion'),
('S0938', 'Skill in interacting with live systems to identify active and historical networks'),
('S0939', 'Skill in performing event analysis'),
('S0940', 'Skill in performing risk-based gap analysis'),
('S0941', 'Skill in identifying gaps in control system network and connectivity architecture'),
('S0942', 'Skill in performing system recovery for control system environments'),
('S0943', 'Skill in connecting to OT assets'),
('S0944', 'Skill in designing and specifying OT systems'),
('S0945', 'Skill in evaluating OT vendor products'),
('S0946', 'Skill in interpreting OT network drawings'),
('S0947', 'Skill in interpreting risk assessments'),
('S0948', 'Skill in performing zone conduit requirement analysis'),
('S0949', 'Skill in recognizing and acknowledging unique contributions from varying skillsets'),
('S0950', 'Skill in reviewing access control lists and firewall rules'),
('S0951', 'Skill in securing control system communication protocols and media');
