INSERT INTO skills (code, description) VALUES
('S0011', 'Skill in conducting information searches'),
('S0015', 'Skill in conducting test events'),
('S0028', 'Skill in developing data dictionaries'),
('S0029', 'Skill in developing data models'),
('S0035', 'Skill in establishing a routing schema'),
('S0045', 'Skill in optimizing database performance'),
('S0048', 'Skill in systems integration testing'),
('S0066', 'Skill in identifying gaps in technical capabilities'),
('S0077', 'Skill in securing network communications'),
('S0080', 'Skill in performing damage assessments'),
('S0097', 'Skill in applying security controls'),
('S0109', 'Skill in identifying hidden patterns or relationships'),
('S0111', 'Skill in interfacing with customers'),
('S0114', 'Skill in performing sensitivity analysis'),
('S0118', 'Skill in developing machine understandable semantic ontologies'),
('S0136', 'Skill in network systems management principles, models, methods (e.g., end-to-end systems performance monitoring), and tools'),
('S0141', 'Skill in assessing security systems designs'),
('S0156', 'Skill in performing packet-level analysis'),
('S0172', 'Skill in applying secure coding techniques'),
('S0175', 'Skill in performing root cause analysis'),
('S0177', 'Skill in performing network analysis on targets'),
('S0186', 'Skill in applying crisis planning procedures'),
('S0194', 'Skill in conducting non-attributable research'),
('S0208', 'Skill in determining the physical location of network devices'),
('S0221', 'Skill in extracting information from packet captures'),
('S0248', 'Skill in performing target system analysis'),
('S0252', 'Skill in processing collected data for follow-on analysis'),
('S0375', 'Skill in developing information requirements'),
('S0378', 'Skill in decrypting information'),
('S0379', 'Skill in verifying participation in a security awareness program'),
('S0380', 'Skill in facilitating cybersecurity awareness briefings'),
('S0381', 'Skill in developing training programs'),
('S0382', 'Skill in tailoring code analysis'),
('S0383', 'Skill in analyzing an organization''s enterprise information technology architecture'),
('S0384', 'Skill in applying standards'),
('S0385', 'Skill in communicating complex concepts'),
('S0386', 'Skill in communicating verbally'),
('S0387', 'Skill in communicating in writing'),
('S0388', 'Skill in facilitating small group discussions'),
('S0389', 'Skill in facilitating group discussions'),
('S0390', 'Skill in assessing learner comprehension'),
('S0391', 'Skill in creating technical documentation'),
('S0392', 'Skill in providing training and education feedback to learners'),
('S0393', 'Skill in developing assessments'),
('S0394', 'Skill in developing security assessments'),
('S0395', 'Skill in developing instructional materials'),
('S0396', 'Skill in forecasting requirements'),
('S0397', 'Skill in assessing requirements'),
('S0398', 'Skill in analyzing organizational objectives'),
('S0399', 'Skill in creating complex data structures'),
('S0400', 'Skill in creating programming languages'),
('S0401', 'Skill in collecting data'),
('S0402', 'Skill in verifying data'),
('S0403', 'Skill in validating data'),
('S0404', 'Skill in conducting market research'),
('S0405', 'Skill in pricing products'),
('S0406', 'Skill in developing policy plans'),
('S0407', 'Skill in developing standard operating procedures (SOPs)'),
('S0408', 'Skill in maintaining standard operating procedures (SOPs)'),
('S0409', 'Skill in deriving evaluative conclusions from data'),
('S0410', 'Skill in creating career path definitions'),
('S0411', 'Skill in developing career paths'),
('S0412', 'Skill in analyzing supplier trustworthiness'),
('S0413', 'Skill in determining supplier trustworthiness'),
('S0414', 'Skill in evaluating laws'),
('S0415', 'Skill in evaluating regulations'),
('S0416', 'Skill in evaluating policies'),
('S0417', 'Skill in deploying software securely'),
('S0418', 'Skill in applying secure network architectures'),
('S0419', 'Skill in designing systems'),
('S0420', 'Skill in integrating multiple technologies'),
('S0421', 'Skill in operating network equipment'),
('S0422', 'Skill in evaluating workforce trends'),
('S0423', 'Skill in analyzing processes to ensure conformance with procedural requirements'),
('S0424', 'Skill in executing command line tools'),
('S0425', 'Skill in operating network systems'),
('S0426', 'Skill in building architectures'),
('S0427', 'Skill in building frameworks'),
('S0428', 'Skill in designing architectures'),
('S0429', 'Skill in designing frameworks'),
('S0430', 'Skill in collaborating with others'),
('S0431', 'Skill in applying critical thinking'),
('S0432', 'Skill in coordinating cybersecurity operations across an organization'),
('S0433', 'Skill in creating analytics'),
('S0434', 'Skill in extrapolating from incomplete data sets'),
('S0435', 'Skill in analyzing large data sets'),
('S0436', 'Skill in creating target intelligence products'),
('S0437', 'Skill in identifying targets of interest'),
('S0438', 'Skill in functioning effectively in a dynamic, fast-paced environment'),
('S0439', 'Skill in identifying external partners'),
('S0440', 'Skill in identifying target vulnerabilities'),
('S0441', 'Skill in describing target vulnerabilities'),
('S0442', 'Skill in collecting network data'),
('S0443', 'Skill in mitigating cognitive biases'),
('S0444', 'Skill in mitigating deception in reporting and analysis'),
('S0446', 'Skill in mimicking threat actors'),
('S0447', 'Skill in aligning privacy and cybersecurity objectives'),
('S0448', 'Skill in creating automated security control systems'),
('S0449', 'Skill in maintaining automated security control systems'),
('S0450', 'Skill in authoring privacy disclosure statements');
