INSERT INTO tasks (code, description) VALUES
('T1719', 'Develop cybersecurity cooperation agreements with external partners'),
('T1732', 'Determine effectiveness of network analysis strategies'),
('T1734', 'Exploit network devices and terminals'),
('T1736', 'Communicate tool requirements to developers'),
('T1737', 'Develop intelligence collection strategies'),
('T1741', 'Designate priority information requirements'),
('T1743', 'Identify information collection gaps'),
('T1747', 'Identify system vulnerabilities within a network'),
('T1758', 'Determine potential implications of new and emerging hardware and software technologies'),
('T1762', 'Modify collection requirements'),
('T1763', 'Determine effectiveness of collection requirements'),
('T1765', 'Monitor changes to designated cyber operations warning problem sets'),
('T1766', 'Prepare change reports for designated cyber operations warning problem sets'),
('T1767', 'Monitor threat activities'),
('T1768', 'Prepare threat activity reports'),
('T1770', 'Report on adversarial activities that fulfill priority information requirements'),
('T1772', 'Identify indications and warnings of target communication changes or processing failures'),
('T1775', 'Prepare cyber operations intelligence reports'),
('T1776', 'Prepare indications and warnings intelligence reports'),
('T1777', 'Conduct policy reviews'),
('T1779', 'Coordinate strategic planning efforts with internal and external partners'),
('T1780', 'Develop external coordination policies'),
('T1781', 'Degrade or remove data from networks and computers'),
('T1784', 'Process exfiltrated data'),
('T1786', 'Profile system administrators and their activities'),
('T1789', 'Provide aim point recommendations for targets'),
('T1790', 'Provide reengagement recommendations'),
('T1792', 'Assess effectiveness of intelligence production'),
('T1793', 'Assess effectiveness of intelligence reporting'),
('T1798', 'Provide intelligence analysis and support'),
('T1799', 'Notify appropriate personnel of imminent hostile intentions or activities'),
('T1801', 'Determine validity and relevance of information'),
('T1802', 'Prepare network reports'),
('T1804', 'Prepare network intrusion reports'),
('T1806', 'Research communications trends in emerging technologies'),
('T1829', 'Evaluate locally developed tools'),
('T1830', 'Test internally developed software'),
('T1831', 'Track status of information requests'),
('T1835', 'Determine if intelligence requirements and collection plans are accurate and up-to-date'),
('T1836', 'Document lessons learned during events and exercises'),
('T1842', 'Identify metadata patterns'),
('T1846', 'Develop natural language processing tools'),
('T1849', 'Communicate critical or time-sensitive information'),
('T1853', 'Determine if new and existing services comply with privacy and data security obligations'),
('T1854', 'Develop and maintain privacy and confidentiality consent forms'),
('T1855', 'Develop and maintain privacy and confidentiality authorization forms'),
('T1856', 'Integrate civil rights and civil liberties in organizational programs, policies, and procedures'),
('T1857', 'Integrate privacy considerations in organizational programs, policies, and procedures'),
('T1858', 'Serve as liaison to regulatory and accrediting bodies'),
('T1859', 'Register databases with local privacy and data protection authorities'),
('T1860', 'Promote privacy awareness to management'),
('T1861', 'Establish organizational Privacy Oversight Committee'),
('T1862', 'Establish cybersecurity risk assessment processes'),
('T1863', 'Develop information sharing strategic plans'),
('T1864', 'Develop organizational information infrastructure'),
('T1865', 'Implement organizational information infrastructure'),
('T1866', 'Develop self-disclosure policies and procedures'),
('T1867', 'Oversee consumer information access rights'),
('T1868', 'Serve as information privacy liaison to technology system users'),
('T1869', 'Serve as liaison to information systems department'),
('T1870', 'Create privacy training materials'),
('T1871', 'Prepare privacy awareness communications'),
('T1872', 'Deliver privacy awareness orientations'),
('T1873', 'Deliver privacy awareness trainings'),
('T1874', 'Manage organizational participation in public privacy and cybersecurity events'),
('T1875', 'Prepare privacy program status reports'),
('T1876', 'Respond to press and other public data security inquiries'),
('T1877', 'Develop organizational privacy program'),
('T1878', 'Apply sanctions for failure to comply with privacy policies'),
('T1879', 'Develop sanctions for failure to comply with privacy policies'),
('T1880', 'Resolve allegations of noncompliance with privacy policies and notice of information practices'),
('T1881', 'Develop a risk management and compliance framework for privacy'),
('T1882', 'Determine if projects comply with organizational privacy and data security policies'),
('T1883', 'Develop organizational privacy policies and procedures'),
('T1884', 'Establish complaint processes'),
('T1885', 'Establish mechanisms to track access to protected health information'),
('T1886', 'Maintain the organizational policy program'),
('T1887', 'Conduct privacy impact assessments'),
('T1888', 'Conduct privacy compliance monitoring'),
('T1889', 'Align cybersecurity and privacy practices in system information security plans'),
('T1890', 'Determine if protected information releases comply with organizational policies and procedures'),
('T1891', 'Administer requests for release or disclosure of protected information'),
('T1892', 'Develop vendor review procedures'),
('T1893', 'Develop vendor auditing procedures'),
('T1894', 'Determine if partner and business agreements address privacy requirements and responsibilities'),
('T1895', 'Provide legal advice for business partner contracts'),
('T1896', 'Mitigate Personal Identifiable Information (PII) breaches'),
('T1897', 'Administer action on organizational privacy complaints'),
('T1898', 'Determine if the organization''s privacy program complies with federal and state privacy laws and regulations'),
('T1899', 'Identify organizational privacy compliance gaps'),
('T1900', 'Correct organizational privacy compliance gaps'),
('T1901', 'Manage privacy breaches'),
('T1902', 'Implement and maintain organizational privacy policies and procedures'),
('T1903', 'Develop and maintain privacy and confidentiality information notices'),
('T1904', 'Determine business partner requirements'),
('T1905', 'Monitor advancements in information privacy technologies'),
('T1906', 'Establish a cybersecurity risk management program'),
('T1907', 'Establish organizational risk management strategies'),
('T1908', 'Determine which business functions a system supports'),
('T1909', 'Determine system stakeholders');
