INSERT INTO tasks (code, description) VALUES
('T1151', 'Develop cybersecurity designs for systems and networks with multilevel security requirements'),
('T1152', 'Develop cybersecurity designs for systems and networks that require processing of multiple data classification levels'),
('T1153', 'Integrate cybersecurity designs for systems and networks'),
('T1154', 'Develop risk, compliance, and assurance monitoring strategies'),
('T1155', 'Develop risk, compliance, and assurance measurement strategies'),
('T1156', 'Develop awareness and training materials'),
('T1157', 'Identify pertinent awareness and training materials'),
('T1158', 'Develop cybersecurity implementation policies and guidelines'),
('T1159', 'Create technical summary of findings reports'),
('T1160', 'Develop risk mitigation strategies'),
('T1161', 'Resolve system vulnerabilities'),
('T1162', 'Recommend security changes to systems and system components'),
('T1163', 'Develop cybersecurity countermeasures for systems and applications'),
('T1164', 'Develop risk mitigation strategies for systems and applications'),
('T1165', 'Develop risk, compliance, and assurance specifications'),
('T1166', 'Document security, resilience, and dependability requirements'),
('T1168', 'Define acquisition life cycle cybersecurity architecture requirements'),
('T1169', 'Define acquisition life cycle systems security engineering requirements'),
('T1170', 'Document preliminary or residual security risks for system operation'),
('T1172', 'Determine if systems security operations and maintenance activities are property documented and updated'),
('T1173', 'Determine that the application of security patches for commercial products meets timeline requirements'),
('T1174', 'Document commercial product timeline requirements dictated by the management authority for intended operational environments'),
('T1175', 'Determine if digital media chain or custody processes meet Federal Rules of Evidence requirements'),
('T1176', 'Determine if cybersecurity-enabled products reduce identified risk to acceptable levels'),
('T1177', 'Determine if security control technologies reduce identified risk to acceptable levels'),
('T1178', 'Determine if security improvement actions are evaluated, validated, and implemented as required'),
('T1179', 'Determine if systems and architecture are consistent with cybersecurity architecture guidelines'),
('T1180', 'Determine if cybersecurity inspections, tests, and reviews are coordinated for the network environment'),
('T1181', 'Determine if cybersecurity requirements are integrated into continuity planning'),
('T1182', 'Determine if security engineering is used when acquiring or developing protection and detection capabilities'),
('T1183', 'Determine if protection and detection capabilities are consistent with organization-level cybersecurity architecture'),
('T1184', 'Establish stakeholder communication channels'),
('T1185', 'Maintain stakeholder communication channels'),
('T1186', 'Establish enterprise information security architecture'),
('T1187', 'Establish internal and external cross-team relationships'),
('T1188', 'Determine if baseline security safeguards are appropriately installed'),
('T1189', 'Determine if contracts comply with funding, legal, and program requirements'),
('T1190', 'Determine hardware configuration'),
('T1191', 'Determine relevance of recovered data'),
('T1192', 'Conduct analysis of computer network attacks'),
('T1193', 'Allocate security functions to components and elements'),
('T1194', 'Remediate technical problems encountered during system testing and implementation'),
('T1195', 'Direct the remediation of technical problems encountered during system testing and implementation'),
('T1196', 'Determine if security incidents are indicative of a violation of law that requires specific legal action'),
('T1197', 'Identify common coding flaws'),
('T1198', 'Identify data or intelligence of evidentiary value'),
('T1199', 'Identify digital evidence for analysis'),
('T1200', 'Identify elements of proof of cybersecurity crimes'),
('T1201', 'Determine implications of new and upgraded technologies to the cybersecurity program'),
('T1202', 'Determine software development security implications within centralized and decentralized environments across the enterprise'),
('T1203', 'Implement software development cybersecurity methodologies within centralized and decentralized environments across the enterprise'),
('T1204', 'Determine cybersecurity measures for steady state operation and management of software'),
('T1205', 'Incorporate product end-of-life cybersecurity measures'),
('T1206', 'Recommend cybersecurity or cybersecurity-enabled products for use within a system'),
('T1207', 'Collect documentary or physical evidence of cyber intrusion incidents, investigations, and operations'),
('T1208', 'Implement new system design procedures'),
('T1209', 'Implement new system test procedures'),
('T1210', 'Implement new system quality standards'),
('T1212', 'Implement cybersecurity countermeasures for systems and applications'),
('T1214', 'Install network infrastructure device operating system software'),
('T1215', 'Maintain network infrastructure device operating system software'),
('T1217', 'Determine if system analysis meets cybersecurity requirements'),
('T1218', 'Integrate automated capabilities for updating or patching system software'),
('T1219', 'Develop processes and procedures for manual updating and patching of system software'),
('T1221', 'Disseminate incident and other Computer Network Defense (CND) information'),
('T1222', 'Determine security requirements for new information technologies'),
('T1223', 'Determine security requirements for new operational technologies'),
('T1224', 'Determine impact of noncompliance on organizational risk levels'),
('T1225', 'Determine impact of noncompliance on effectiveness of the enterprise''s cybersecurity program'),
('T1226', 'Align cybersecurity priorities with organizational security strategy'),
('T1227', 'Manage cybersecurity budget, staffing, and contracting'),
('T1228', 'Maintain baseline system security'),
('T1229', 'Maintain deployable cyber defense audit toolkits'),
('T1230', 'Maintain directory replication services'),
('T1231', 'Maintain information exchanges through publish, subscribe, and alert functions'),
('T1232', 'Approve accreditation packages'),
('T1233', 'Monitor cybersecurity data sources'),
('T1234', 'Develop Computer Network Defense (CND) guidance for organizational stakeholders'),
('T1235', 'Manage threat and target analysis'),
('T1236', 'Manage the production of threat information'),
('T1237', 'Determine if systems comply with security, resilience, and dependability requirements'),
('T1238', 'Determine the effectiveness of enterprise cybersecurity safeguards'),
('T1239', 'Monitor the usage of knowledge management assets and resources'),
('T1240', 'Create knowledge management assets and resources usage reports'),
('T1241', 'Document cybersecurity incidents'),
('T1242', 'Escalate incidents that may cause ongoing and immediate impact to the environment'),
('T1243', 'Oversee configuration management'),
('T1244', 'Develop configuration management recommendations'),
('T1245', 'Oversee the cybersecurity training and awareness program'),
('T1246', 'Establish Security Assessment and Authorization processes'),
('T1247', 'Develop computer environment cybersecurity plans and requirements'),
('T1248', 'Patch network vulnerabilities'),
('T1249', 'Perform backup and recovery of databases'),
('T1250', 'Perform cyber defense incident triage'),
('T1251', 'Recommend incident remediation strategies'),
('T1252', 'Determine the scope, urgency, and impact of cyber defense incidents'),
('T1253', 'Perform dynamic analysis on drives'),
('T1254', 'Determine the effectiveness of an observed attack'),
('T1255', 'Perform cybersecurity testing of developed applications and systems'),
('T1256', 'Perform forensically sound image collection');
