INSERT INTO tasks (code, description) VALUES
('T1910', 'Identify common controls available for inheritance by organizational systems'),
('T1911', 'Determine the security categorization for organizational systems'),
('T1912', 'Determine system boundaries'),
('T1913', 'Identify system security requirements'),
('T1914', 'Register systems with organizational program management offices'),
('T1915', 'Identify required system security controls'),
('T1916', 'Document planned system security control implementations'),
('T1917', 'Establish security control monitoring strategies'),
('T1918', 'Review and approve System Security Plans (SSPs)'),
('T1919', 'Implement system security controls'),
('T1920', 'Establish system configuration baselines'),
('T1921', 'Document changes to planned system control implementations'),
('T1922', 'Develop system security control assessment plans'),
('T1923', 'Approve system security control assessment plans'),
('T1924', 'Determine effectiveness of security controls'),
('T1925', 'Prepare security control assessment reports'),
('T1926', 'Conduct security control remediations'),
('T1927', 'Develop cybersecurity action plans and milestones'),
('T1928', 'Prepare authorization packages'),
('T1929', 'Submit authorization packages to authorizing officials for adjudication'),
('T1930', 'Determine risks of operating or using a system'),
('T1931', 'Determine risks of using common controls'),
('T1932', 'Implement cybersecurity action plans'),
('T1933', 'Determine if system security risks are acceptable'),
('T1934', 'Determine if common control risks are acceptable'),
('T1935', 'Update cybersecurity action plans'),
('T1936', 'Report system security status to authorizing officials'),
('T1937', 'Determine if system security meets acceptable risk levels'),
('T1938', 'Establish system disposal processes'),
('T1939', 'Implement system disposal processes'),
('T1940', 'Form continuous monitoring working groups'),
('T1941', 'Establish continuous monitoring scoring and grading metrics'),
('T1942', 'Integrate a continuous monitoring program into organizational security governance structures and policies'),
('T1943', 'Make cybersecurity investment decisions to address persistent issues'),
('T1944', 'Provide training and resources to continuous monitoring staff'),
('T1945', 'Prepare continuous monitoring reports'),
('T1946', 'Determine if risk metrics support continuous monitoring'),
('T1947', 'Determine if continuous monitoring data provides situational awareness of risk levels'),
('T1948', 'Define unacceptable risk threshold triggers for continuous monitoring data'),
('T1949', 'Establish system-level reporting categories'),
('T1950', 'Manage the continuous monitoring program'),
('T1951', 'Establish continuous monitoring communication processes'),
('T1952', 'Identify reporting requirements that are fulfilled by the continuous monitoring program'),
('T1953', 'Establish continuous monitoring reporting requirements'),
('T1954', 'Perform continuous monitoring'),
('T1955', 'Establish automated control assessment reporting requirements'),
('T1956', 'Conduct continuous monitoring data assessments'),
('T1957', 'Integrate continuous monitoring results in ongoing authorizations'),
('T1958', 'Establish access control processes for continuous monitoring tools and technologies'),
('T1959', 'Implement access control processes for continuous monitoring tools and technologies'),
('T1960', 'Establish technical help processes for continuous monitoring mitigators'),
('T1961', 'Communicate continuous monitoring reporting requirements'),
('T1962', 'Define responsibilities for implementing continuous monitoring tools or technologies'),
('T1963', 'Establish liaison to scoring and metrics working group'),
('T1964', 'Establish risk management processes'),
('T1965', 'Establish performance measurement requirements for continuous monitoring tools and technologies'),
('T1966', 'Assess continuous monitoring performance'),
('T1967', 'Coordinate responses to issues flagged during continuous monitoring'),
('T1968', 'Implement risk mitigation strategies'),
('T1969', 'Document system alerts'),
('T1970', 'Escalate system alerts that may indicate risks'),
('T1971', 'Disseminate anomalous activity reports to the insider threat hub'),
('T1972', 'Identify anomalous activity'),
('T1973', 'Conduct independent comprehensive assessments of target-specific information'),
('T1974', 'Conduct insider threat risk assessments'),
('T1975', 'Prepare insider threat briefings'),
('T1976', 'Recommend risk mitigation courses of action (CoA)'),
('T1977', 'Coordinate with internal and external incident management partners across jurisdictions'),
('T1978', 'Recommend improvements to insider threat detection processes'),
('T1979', 'Collect digital evidence that meets priority intelligence requirements'),
('T1980', 'Develop digital evidence reports for internal and external partners'),
('T1981', 'Develop elicitation indicators'),
('T1982', 'Identify high value assets'),
('T1983', 'Identify potential insider threats'),
('T1984', 'Notify appropriate personnel of imminent of imminent hostile intentions or activities'),
('T1985', 'Identify imminent or hostile intentions or activities'),
('T1986', 'Develop a continuously updated overview of an incident throughout the incident''s life cycle'),
('T1987', 'Develop insider threat cyber operations indicators'),
('T1988', 'Integrate information from cyber resources, internal partners, and external partners'),
('T1989', 'Advise insider threat hub inquiries'),
('T1990', 'Conduct cybersecurity insider threat inquiries'),
('T1991', 'Deliver all-source cyber operations and intelligence indications and warnings'),
('T1992', 'Interpret network activity for intelligence value'),
('T1993', 'Monitor network activity for vulnerabilities'),
('T1994', 'Identify potential insider risks to networks'),
('T1995', 'Document potential insider risks to networks'),
('T1996', 'Report network vulnerabilities'),
('T1997', 'Develop insider threat investigation plans'),
('T1998', 'Investigate alleged insider threat cybersecurity policy violations'),
('T1999', 'Refer cases on active insider threat activities to law enforcement investigators'),
('T2000', 'Perform cybersecurity reviews'),
('T2001', 'Establish an insider threat risk management assessment program'),
('T2002', 'Recommend courses of action or countermeasures to mitigate risks'),
('T2003', 'Evaluate organizational insider risk response capabilities'),
('T2004', 'Document insider threat information sources'),
('T2005', 'Conduct insider threat studies'),
('T2006', 'Identify potential targets for exploitation'),
('T2007', 'Analyze potential targets for exploitation'),
('T2008', 'Vet insider threat targeting with law enforcement and intelligence partners'),
('T2009', 'Develop insider threat targets');
