INSERT INTO tasks (code, description) VALUES
('T1257', 'Recommend mitigation and remediation strategies for enterprise systems'),
('T1258', 'Perform integrated quality assurance testing'),
('T1259', 'Identify opportunities for new and improved business process solutions'),
('T1260', 'Perform real-time cyber defense incident handling'),
('T1261', 'Mitigate programming vulnerabilities'),
('T1262', 'Identify programming code flaws'),
('T1263', 'Perform security reviews'),
('T1264', 'Identify gaps in security architecture'),
('T1265', 'Develop a cybersecurity risk management plan'),
('T1266', 'Recommend risk mitigation strategies'),
('T1267', 'Perform system administration on specialized cyber defense applications and systems'),
('T1268', 'Administer Virtual Private Network (VPN) devices'),
('T1269', 'Conduct risk analysis of applications and systems undergoing major changes'),
('T1270', 'Plan security authorization reviews for system and network installations'),
('T1271', 'Conduct security authorization reviews for system and network installations'),
('T1272', 'Develop security assurance cases for system and network installations'),
('T1273', 'Plan knowledge management projects'),
('T1274', 'Deliver knowledge management projects'),
('T1275', 'Determine the effectiveness of data redundancy and system recovery procedures'),
('T1276', 'Develop data redundancy and system recovery procedures'),
('T1277', 'Execute data redundancy and system recovery procedures'),
('T1278', 'Recommend system modifications'),
('T1279', 'Prepare audit reports'),
('T1280', 'Develop workflow charts and diagrams'),
('T1281', 'Convert workflow charts and diagrams into coded computer language instructions'),
('T1282', 'Prepare digital media for imaging'),
('T1283', 'Develop cybersecurity use cases'),
('T1284', 'Develop standard operating procedures for secure network system operations'),
('T1285', 'Distribute standard operating procedures'),
('T1286', 'Maintain standard operating procedures'),
('T1287', 'Document systems security activities'),
('T1288', 'Prepare technical evaluations of software applications, systems, and networks'),
('T1289', 'Document software application, system, and network security postures, capabilities, and vulnerabilities'),
('T1290', 'Communicate daily network event and activity reports'),
('T1291', 'Advise stakeholders on the development of continuity of operations plans'),
('T1292', 'Develop guidelines for implementing developed systems for customers and installation teams'),
('T1293', 'Advise on security requirements to be included in statements of work'),
('T1294', 'Advise on Risk Management Framework process activities and documentation'),
('T1295', 'Provide cybersecurity awareness and training'),
('T1296', 'Recommend data structures for use in the production of reports'),
('T1297', 'Recommend new database technologies and architectures'),
('T1298', 'Communicate situational awareness information to leadership'),
('T1299', 'Determine causes of network alerts'),
('T1300', 'Report cybersecurity incidents'),
('T1301', 'Report forensic artifacts indicative of a particular operating system'),
('T1302', 'Address security implications in the software acceptance phase'),
('T1303', 'Recommend new or revised security, resilience, and dependability measures'),
('T1304', 'Recommend organizational cybersecurity resource allocations'),
('T1305', 'Determine if authorization and assurance documents identify an acceptable level of risk for software applications, systems, and networks'),
('T1306', 'Conduct technology program and project audits'),
('T1307', 'Develop cybersecurity policy recommendations'),
('T1308', 'Coordinate cybersecurity policy review and approval processes'),
('T1309', 'Analyze system capabilities and requirements'),
('T1310', 'Implement protective or corrective measures when a cybersecurity incident or vulnerability is discovered'),
('T1311', 'Design and execute exercise scenarios'),
('T1312', 'Conduct test and evaluation activities'),
('T1313', 'Test network infrastructure, including software and hardware devices'),
('T1314', 'Maintain network infrastructure, including software and hardware devices'),
('T1315', 'Track cyber defense incidents from initial detection through final resolution'),
('T1316', 'Document cyber defense incidents from initial detection through final resolution'),
('T1317', 'Determine if appropriate threat mitigation actions have been taken'),
('T1318', 'Integrate security requirements into application design elements'),
('T1319', 'Document software attack surface elements'),
('T1320', 'Conduct threat modeling'),
('T1321', 'Manage computing environment system operations'),
('T1322', 'Capture network traffic associated with malicious activities'),
('T1323', 'Analyze network traffic associated with malicious activities'),
('T1324', 'Process digital evidence'),
('T1325', 'Document digital evidence'),
('T1326', 'Develop system performance predictions for various operating conditions'),
('T1327', 'Update security documentation to reflect current application and system security design features'),
('T1328', 'Verify implementation of software, network, and system cybersecurity postures'),
('T1329', 'Document software, network, and system deviations from implemented security postures'),
('T1330', 'Recommend required actions to correct software, network, and system deviations from implemented security postures'),
('T1331', 'Verify currency of software application, network, and system accreditation and assurance documentation'),
('T1332', 'Produce incident findings reports'),
('T1333', 'Communicate incident findings to appropriate constituencies'),
('T1334', 'Produce cybersecurity instructional materials'),
('T1335', 'Promote cybersecurity awareness to management'),
('T1336', 'Verify the inclusion of sound cybersecurity principles in the organization''s vision and goals'),
('T1337', 'Identify system and network capabilities'),
('T1338', 'Develop cybersecurity capability strategies for custom hardware and software development'),
('T1339', 'Develop cybersecurity compliance processes for external services'),
('T1340', 'Develop cybersecurity audit processes for external services'),
('T1341', 'Perform required reviews'),
('T1342', 'Oversee policy standards and implementation strategy development'),
('T1343', 'Provide cybersecurity guidance to organizational risk governance processes'),
('T1344', 'Determine if procurement activities sufficiently address supply chain risks'),
('T1345', 'Recommend improvements to procurement activities to address cybersecurity requirements'),
('T1346', 'Determine if system requirements are adequately demonstrated in data samples'),
('T1347', 'Detect cybersecurity attacks and intrusions'),
('T1348', 'Distinguish between benign and potentially malicious cybersecurity attacks and intrusions'),
('T1349', 'Communicate cybersecurity attacks and intrusions alerts'),
('T1350', 'Perform continuous monitoring of system activity'),
('T1351', 'Determine impact of malicious activity on systems and information'),
('T1352', 'Coordinate critical cyber defense infrastructure protection measures'),
('T1353', 'Prioritize critical cyber defense infrastructure resources'),
('T1354', 'Identify system cybersecurity requirements'),
('T1355', 'Determine if vulnerability remediation plans are in place'),
('T1356', 'Develop vulnerability remediation plans');
