INSERT INTO tasks (code, description) VALUES
('T1357', 'Determine if cybersecurity requirements have been successfully implemented'),
('T1358', 'Determine the effectiveness of organizational cybersecurity policies and procedures'),
('T1359', 'Perform penetration testing'),
('T1360', 'Design programming language exploitation countermeasures and mitigations'),
('T1361', 'Determine the impact of new system and interface implementations on organization''s cybersecurity posture'),
('T1362', 'Document impact of new system and interface implementations on organization''s cybersecurity posture'),
('T1363', 'Plan system security development'),
('T1364', 'Conduct system security development'),
('T1365', 'Document cybersecurity design and development activities'),
('T1366', 'Identify supply chain risks for critical system elements'),
('T1367', 'Document supply chain risks for critical system elements'),
('T1368', 'Support cybersecurity compliance activities'),
('T1369', 'Determine if acquisitions, procurement, and outsourcing efforts address cybersecurity requirements'),
('T1370', 'Collect intrusion artifacts'),
('T1371', 'Mitigate potential cyber defense incidents'),
('T1372', 'Advise law enforcement personnel as technical expert'),
('T1373', 'Determine organizational compliance'),
('T1374', 'Forecast ongoing service demands'),
('T1375', 'Conduct periodic reviews of security assumptions'),
('T1376', 'Develop critical infrastructure protection policies and procedures'),
('T1377', 'Implement critical infrastructure protection policies and procedures'),
('T1378', 'Identify cybersecurity solutions tools and technologies'),
('T1379', 'Design cybersecurity tools and technologies'),
('T1380', 'Develop cybersecurity tools and technologies'),
('T1381', 'Scan digital media for viruses'),
('T1382', 'Mount a drive image'),
('T1383', 'Utilize deployable forensics toolkit'),
('T1384', 'Establish intrusion set procedures'),
('T1386', 'Analyze network traffic anomalies'),
('T1387', 'Validate intrusion detection system alerts'),
('T1388', 'Isolate malware'),
('T1389', 'Remove malware'),
('T1390', 'Identify network device applications and operating systems'),
('T1391', 'Reconstruct malicious attacks'),
('T1392', 'Develop user experience requirements'),
('T1393', 'Document user experience requirements'),
('T1394', 'Develop independent cybersecurity audit processes for application software, networks, and systems'),
('T1395', 'Implement independent cybersecurity audit processes for application software, networks, and systems'),
('T1396', 'Oversee independent cybersecurity audits'),
('T1397', 'Determine if research and design processes and procedures are in compliance with cybersecurity requirements'),
('T1398', 'Determine if research and design processes and procedures are accurately followed by cybersecurity staff when performing their day-to-day activities'),
('T1399', 'Develop supply chain, system, network, and operational security contract language'),
('T1400', 'Design and develop secure applications'),
('T1401', 'Integrate system development life cycle methodologies into development environment'),
('T1402', 'Manage databases and data management systems'),
('T1403', 'Allocate cybersecurity services'),
('T1404', 'Select cybersecurity mechanisms'),
('T1405', 'Identify emerging incident trends'),
('T1406', 'Construct cyber defense network tool signatures'),
('T1407', 'Correlate threat assessment data'),
('T1408', 'Develop quality standards'),
('T1409', 'Document quality standards'),
('T1410', 'Develop system security contexts'),
('T1411', 'Develop technical training curriculum and resources'),
('T1412', 'Deliver technical training to customers'),
('T1413', 'Develop training modules and classes'),
('T1414', 'Develop training assignments'),
('T1415', 'Develop training evaluations'),
('T1416', 'Develop grading and proficiency standards'),
('T1417', 'Create learner development, training, and remediation plans'),
('T1418', 'Develop learning objectives and goals'),
('T1419', 'Develop organizational training materials'),
('T1420', 'Develop organizational training programs'),
('T1421', 'Develop proficiency assessments'),
('T1422', 'Develop software documentation'),
('T1423', 'Create system security concept of operations (ConOps) documents'),
('T1424', 'Evaluate network infrastructure vulnerabilities'),
('T1425', 'Recommend network infrastructure enhancements'),
('T1426', 'Determine cybersecurity design and architecture effectiveness'),
('T1427', 'Maintain incident tracking and solution databases'),
('T1428', 'Notify designated managers, cyber incident responders, and cybersecurity service provider team members of suspected cybersecurity incidents'),
('T1429', 'Prepare trend analysis reports'),
('T1430', 'Determine if system components can be aligned'),
('T1431', 'Integrate system components'),
('T1432', 'Build dedicated cyber defense hardware'),
('T1433', 'Install dedicated cyber defense hardware'),
('T1434', 'Create cybersecurity architecture functional specifications'),
('T1435', 'Determine if technology services are delivered successfully'),
('T1436', 'Acquire adequate funding for cybersecurity training'),
('T1437', 'Determine effectiveness of configuration management processes'),
('T1438', 'Determine effectiveness of instruction and training'),
('T1439', 'Assess the behavior of individual victims, witnesses, or suspects during cybersecurity investigations'),
('T1440', 'Assess the validity of source data'),
('T1441', 'Determine the validity of findings'),
('T1442', 'Assess the impact of implementing and sustaining a dedicated cyber defense infrastructure'),
('T1443', 'Recommend commercial, government off-the-shelf, or open source products for use within a system'),
('T1444', 'Determine if products comply with cybersecurity requirements'),
('T1445', 'Conduct hypothesis testing'),
('T1446', 'Conduct learning needs assessments'),
('T1447', 'Identify training requirements'),
('T1448', 'Manage customer services'),
('T1449', 'Determine if qualification standards meet organizational functional requirements and comply with industry standards'),
('T1450', 'Allocate and distribute human capital assets'),
('T1451', 'Create interactive learning exercises'),
('T1452', 'Design system administration and management functionality for privileged access users'),
('T1453', 'Develop system administration and management functionality for privileged access users'),
('T1454', 'Design secure interfaces between information systems, physical systems, and embedded technologies'),
('T1455', 'Implement secure interfaces between information systems, physical systems, and embedded technologies'),
('T1456', 'Determine the impact of threats on cybersecurity'),
('T1457', 'Implement threat countermeasures');
