INSERT INTO tasks (code, description) VALUES
('T1560', 'Mitigate risks in systems and system components'),
('T1561', 'Implement dedicated cyber defense systems'),
('T1562', 'Document system requirements'),
('T1563', 'Implement system security measures'),
('T1564', 'Install database management systems and software'),
('T1565', 'Configure database management systems and software'),
('T1566', 'Install system hardware, software, and peripheral equipment'),
('T1567', 'Configure system hardware, software, and peripheral equipment'),
('T1568', 'Implement cross-domain solutions'),
('T1569', 'Administer system and network user accounts'),
('T1570', 'Establish system and network rights processes and procedures'),
('T1571', 'Establish systems and equipment access protocols'),
('T1572', 'Inventory technology resources'),
('T1573', 'Determine if developed solutions meet customer requirements'),
('T1574', 'Develop risk acceptance documentation for senior leaders and authorized representatives'),
('T1575', 'Adapt software to new hardware'),
('T1576', 'Upgrade software interfaces'),
('T1577', 'Improve software performance'),
('T1578', 'Monitor system and server configurations'),
('T1579', 'Maintain system and server configurations'),
('T1580', 'Monitor client-level computer system performance'),
('T1581', 'Create client-level computer system performance reports'),
('T1582', 'Maintain currency of cyber defense threat conditions'),
('T1583', 'Determine effectiveness of system implementation and testing processes'),
('T1584', 'Establish minimum security requirements for applications'),
('T1585', 'Determine if applications meet minimum security requirements'),
('T1586', 'Conduct cybersecurity risk assessments'),
('T1587', 'Perform cybersecurity testing on systems in development'),
('T1588', 'Diagnose faulty system and server hardware'),
('T1589', 'Repair faulty system and server hardware'),
('T1590', 'Identify programming flaws'),
('T1591', 'Address security architecture gaps'),
('T1592', 'Conduct cybersecurity reviews'),
('T1593', 'Identify cybersecurity gaps in enterprise architecture'),
('T1594', 'Plan classroom learning sessions'),
('T1595', 'Coordinate training and education'),
('T1596', 'Plan delivery of non-classroom learning'),
('T1597', 'Plan implementation strategies'),
('T1598', 'Assess the integration and alignment capabilities of enterprise components'),
('T1599', 'Prepare legal documents'),
('T1600', 'Prepare investigative reports'),
('T1601', 'Advise stakeholders on enterprise cybersecurity risk management'),
('T1602', 'Advise stakeholders on supply chain risk management'),
('T1603', 'Recommend threat and vulnerability risk mitigation strategies'),
('T1604', 'Provide cybersecurity advice on implementation plans, standard operating procedures, maintenance documentation, and maintenance training materials'),
('T1605', 'Advise management, staff, and users on cybersecurity policy'),
('T1606', 'Prepare impact reports'),
('T1607', 'Recover information from forensic data sources'),
('T1608', 'Perform periodic reviews of learning materials and courses for accuracy and currency'),
('T1609', 'Recommend revisions to learning materials and curriculum'),
('T1610', 'Determine if hardware and software complies with defined specifications and requirements'),
('T1611', 'Record test data'),
('T1612', 'Manage test data'),
('T1613', 'Determine if design components meet system requirements'),
('T1614', 'Determine scalability of system architecture'),
('T1615', 'Advise stakeholders on vulnerability compliance'),
('T1616', 'Resolve computer security incidents'),
('T1617', 'Prepare cyber defense reports'),
('T1618', 'Advise stakeholders on disaster recovery, contingency, and continuity of operations plans'),
('T1619', 'Perform risk and vulnerability assessments'),
('T1620', 'Recommend cost-effective security controls'),
('T1621', 'Prepare supply chain security reports'),
('T1622', 'Prepare risk management reports'),
('T1623', 'Develop supply chain cybersecurity risk management policy'),
('T1624', 'Conduct vulnerability analysis of software patches and updates'),
('T1625', 'Prepare vulnerability analysis reports'),
('T1626', 'Determine impact of new systems and system interfaces on current and target environments'),
('T1627', 'Conduct cybersecurity management assessments'),
('T1628', 'Design cybersecurity management functions'),
('T1639', 'Assess target vulnerabilities and operational capabilities'),
('T1640', 'Determine effectiveness of intelligence collection operations'),
('T1641', 'Recommend adjustments to intelligence collection strategies'),
('T1643', 'Develop common operational pictures'),
('T1644', 'Develop cyber operations indicators'),
('T1645', 'Coordinate all-source collection activities'),
('T1646', 'Validate all-source collection requirements and plans'),
('T1647', 'Develop priority information requirements'),
('T1648', 'Develop performance success metrics'),
('T1650', 'Develop cybersecurity success metrics'),
('T1651', 'Prepare threat and target briefings'),
('T1652', 'Prepare threat and target situational updates'),
('T1658', 'Determine customer requirements'),
('T1666', 'Exploit wireless computer and digital networks'),
('T1669', 'Analyze system vulnerabilities within a network'),
('T1670', 'Conduct on-net activities'),
('T1671', 'Exfiltrate data from deployed technologies'),
('T1672', 'Conduct off-net activities'),
('T1676', 'Survey computer and digital networks'),
('T1679', 'Develop organizational decision support tools'),
('T1686', 'Identify intelligence requirements'),
('T1689', 'Create comprehensive exploitation strategies'),
('T1690', 'Identify exploitable technical or operational vulnerabilities'),
('T1698', 'Collect target information'),
('T1699', 'Develop crisis plans'),
('T1700', 'Maintain crisis plans'),
('T1708', 'Prepare operational assessment reports'),
('T1712', 'Recommend potential courses of action'),
('T1713', 'Develop feedback procedures'),
('T1717', 'Recommend changes to planning policies and procedures'),
('T1718', 'Implement changes to planning policies and procedures');
