INSERT INTO tasks (code, description) VALUES
('T1049', 'Determine appropriate level of test rigor for a given system'),
('T1050', 'Improve network security practices'),
('T1051', 'Set up a forensic workstation'),
('T1052', 'Integrate black-box security testing tools into quality assurance processes'),
('T1053', 'Identify and characterize intrusion activities against a victim or target'),
('T1054', 'Scope analysis reports to various audiences that accounts for data sharing classification restrictions'),
('T1055', 'Determine if priority information requirements are satisfied'),
('T1056', 'Acquire resources to support cybersecurity program goals and objectives'),
('T1057', 'Conduct an effective enterprise continuity of operations program'),
('T1058', 'Advise senior management on risk levels and security posture'),
('T1059', 'Perform cost/benefit analyses of cybersecurity programs, policies, processes, systems, and elements'),
('T1060', 'Advise senior management on organizational cybersecurity efforts'),
('T1061', 'Advise senior leadership and authorizing official of changes affecting the organization''s cybersecurity posture'),
('T1062', 'Contribute insider threat expertise to organizational cybersecurity awareness program'),
('T1063', 'Determine data requirements'),
('T1064', 'Determine data specifications'),
('T1065', 'Determine data capacity requirements'),
('T1066', 'Plan for anticipated changes in data capacity requirements'),
('T1067', 'Recommend development of new applications or modification of existing applications'),
('T1068', 'Create development plans for new applications or modification of existing applications'),
('T1069', 'Evaluate organizational cybersecurity policy regulatory compliance'),
('T1070', 'Evaluate organizational cybersecurity policy alignment with organizational directives'),
('T1071', 'Evaluate software design plan timelines and cost estimates'),
('T1072', 'Determine life cycle support requirements'),
('T1073', 'Perform code reviews'),
('T1074', 'Prepare secure code documentation'),
('T1075', 'Implement application cybersecurity policies'),
('T1076', 'Implement system cybersecurity policies'),
('T1077', 'Assess the organization''s cybersecurity architecture'),
('T1078', 'Determine effectiveness of system cybersecurity measures'),
('T1079', 'Develop cybersecurity risk profiles'),
('T1081', 'Create product prototypes using working and theoretical models'),
('T1082', 'Integrate software cybersecurity objectives into project plans and schedules'),
('T1083', 'Determine project security controls'),
('T1084', 'Identify anomalous network activity'),
('T1085', 'Identify potential threats to network resources'),
('T1086', 'Collect and maintain system cybersecurity report data'),
('T1087', 'Create system cybersecurity reports'),
('T1088', 'Communicate the value of cybersecurity to organizational stakeholders'),
('T1089', 'Create program documentation during initial development and subsequent revision phases'),
('T1090', 'Determine best methods for identifying the perpetrator(s) of a network intrusion'),
('T1091', 'Perform authorized penetration testing on enterprise network assets'),
('T1092', 'Conduct functional and connectivity testing'),
('T1093', 'Conduct interactive training exercises'),
('T1094', 'Conduct victim and witness interviews'),
('T1095', 'Conduct suspect interrogations'),
('T1096', 'Perform privacy impact assessments (PIAs)'),
('T1097', 'Determine functional requirements and specifications'),
('T1098', 'Determine system performance requirements'),
('T1099', 'Design application interfaces'),
('T1100', 'Configure network hubs, routers, and switches'),
('T1101', 'Optimize network hubs, routers, and switches'),
('T1102', 'Identify intrusions'),
('T1103', 'Analyze intrusions'),
('T1104', 'Document what is known about intrusions'),
('T1105', 'Construct access paths to suites of information'),
('T1106', 'Develop threat models'),
('T1107', 'Evaluate functional requirements'),
('T1108', 'Evaluate interfaces between hardware and software'),
('T1109', 'Resolve cyber defense incidents'),
('T1110', 'Coordinate technical support to enterprise-wide cybersecurity defense technicians'),
('T1111', 'Administer rule and signature updates for specialized cyber defense applications'),
('T1112', 'Validate network alerts'),
('T1113', 'Develop the enterprise continuity of operations strategy'),
('T1114', 'Establish the enterprise continuity of operations program'),
('T1115', 'Oversee the development of design solutions'),
('T1116', 'Correct program errors'),
('T1117', 'Determine if desired program results are produced'),
('T1118', 'Identify vulnerabilities'),
('T1119', 'Recommend vulnerability remediation strategies'),
('T1120', 'Create forensically sound duplicates of evidence'),
('T1121', 'Decrypt seized data'),
('T1122', 'Determine essential system capabilities and business functions'),
('T1123', 'Prioritize essential system capabilities and business functions'),
('T1124', 'Restore essential system capabilities and business functions after catastrophic failure events'),
('T1125', 'Define system availability levels'),
('T1126', 'Determine disaster recovery and continuity of operations system requirements'),
('T1127', 'Define project scope and objectives'),
('T1128', 'Design cybersecurity or cybersecurity-enabled products'),
('T1129', 'Develop cybersecurity or cybersecurity-enabled products'),
('T1130', 'Develop group policies and access control lists'),
('T1131', 'Determine if hardware, operating systems, and software applications adequately address cybersecurity requirements'),
('T1132', 'Design system data backup capabilities'),
('T1133', 'Develop technical and procedural processes for integrity of stored backup data'),
('T1134', 'Develop technical and procedural processes for backup data storage'),
('T1135', 'Design and develop software systems'),
('T1136', 'Determine level of assurance of developed capabilities'),
('T1137', 'Investigate suspicious activity and alleged digital crimes'),
('T1138', 'Create system testing and validation procedures and documentation'),
('T1139', 'Develop systems design procedures and processes'),
('T1140', 'Develop systems administration standard operating procedures'),
('T1141', 'Document systems administration standard operating procedures'),
('T1142', 'Validate data mining and data warehousing programs, processes, and requirements'),
('T1143', 'Develop network backup and recovery procedures'),
('T1144', 'Implement network backup and recovery procedures'),
('T1145', 'Develop strategic plans'),
('T1146', 'Maintain strategic plans'),
('T1148', 'Develop systems security design documentation'),
('T1149', 'Develop disaster recovery and continuity of operations plans for systems under development'),
('T1150', 'Test disaster recovery and continuity of operations plans for systems prior to deployment');
