INSERT INTO tasks (code, description) VALUES
('T2010', 'Maintain User Activity Monitoring (UAM) tools'),
('T2011', 'Monitor the output from User Activity Monitoring (UAM) tools'),
('T2012', 'Check network connections'),
('T2013', 'Look for indicators of intrusions'),
('T2014', 'Identify devices and networks on scene'),
('T2015', 'Collect devices containing digital evidence'),
('T2016', 'Identify areas of compromise'),
('T2017', 'Acquire digital evidence'),
('T2018', 'Create a digital footprint of raw or physical data'),
('T2019', 'Process data into readable format'),
('T2020', 'Prepare data for ingestion into application systems'),
('T2021', 'Recover deleted or overwritten data files'),
('T2022', 'Create derivative evidence from findings report'),
('T2023', 'Serve as subject expert in training fact witnesses for testifying'),
('T2024', 'Present factual causality to support attribution of criminal activity'),
('T2025', 'Prepare technical materials for legal proceedings'),
('T2026', 'Serve as liaison to prosecutors'),
('T2027', 'Manage forensic laboratory accreditation processes'),
('T2028', 'Develop OT inventory model for cybersecurity '),
('T2029', 'Serve as OT engineering subject matter expert during development of change management policies and procedures'),
('T2030', 'Determine if implementation of security measures and controls meets regulatory standards and is in compliance with legal or policy requirements'),
('T2031', 'Identify gaps in OT network architecture'),
('T2032', 'Assign security level targets to network zones for control systems'),
('T2033', 'Create a change management plan'),
('T2034', 'Design cybersecurity tools for OT systems'),
('T2035', 'Perform a process hazard analysis (PHA)'),
('T2036', 'Review policies, standards, and regulations for conflicts that may create control system vulnerabilities'),
('T2037', 'Create cybersecurity inspection and test policies and procedures for OT systems'),
('T2038', 'Develop system procurement specifications'),
('T2039', 'Determine the impact of cybersecurity requirements on costs and budgeting'),
('T2040', 'Conduct cybersecurity reviews of OT system engineering plans and documentation'),
('T2041', 'Participate in safety system design processes to counteract potential cybersecurity sabotage'),
('T2042', 'Generate cyberattack scenarios of serious physical consequence'),
('T2043', 'Oversee implementation of system controls'),
('T2044', 'Develop system upgrade specifications'),
('T2045', 'Assign networked engineering assets to security zones'),
('T2046', 'Communicate implication of new and upgraded technologies to cybersecurity program stakeholders'),
('T2047', 'Inventory OT assets'),
('T2048', 'Recommend cybersecurity requirements for integration in continuity planning'),
('T2049', 'Serve as OT engineering subject matter expert for cybersecurity standards, policies, and procedures development'),
('T2050', 'Serve as OT engineering subject matter expert for development of organizational cybersecurity risk management plan'),
('T2051', 'Train cybersecurity defense technicians on OT system processes and procedures');
