INSERT INTO tasks (code, description) VALUES
('T1458', 'Develop data gathering processes'),
('T1459', 'Develop standardized cybersecurity position descriptions using the NICE Framework'),
('T1460', 'Develop recruiting, hiring, and retention processes'),
('T1461', 'Determine cybersecurity position requirements'),
('T1462', 'Develop cybersecurity training policies and procedures'),
('T1463', 'Develop cybersecurity curriculum goals and objectives'),
('T1464', 'Determine if cybersecurity workforce management policies and procedures comply with legal and organizational requirements'),
('T1465', 'Define service-level agreements (SLAs)'),
('T1466', 'Establish cybersecurity workforce readiness metrics'),
('T1467', 'Establish waiver processes for cybersecurity career field entry and training qualification requirements'),
('T1468', 'Establish organizational cybersecurity career pathways'),
('T1469', 'Develop cybersecurity workforce reporting requirements'),
('T1470', 'Establish cybersecurity workforce management programs'),
('T1471', 'Assess cybersecurity workforce management programs'),
('T1472', 'Gather customer satisfaction and service performance feedback'),
('T1473', 'Create risk-driven systems maintenance and updates processes'),
('T1474', 'Define operating level agreements (OLAs)'),
('T1475', 'Develop instructional strategies'),
('T1476', 'Promote awareness of cybersecurity policy and strategy among management'),
('T1477', 'Advise trial counsel as technical expert'),
('T1478', 'Determine cybersecurity career field qualification requirements'),
('T1479', 'Determine organizational policies related to or influencing the cyber workforce'),
('T1480', 'Examine service performance reports for issues and variances'),
('T1481', 'Initiate corrective actions to service performance issues and variances'),
('T1482', 'Conduct cybersecurity workforce assessments'),
('T1483', 'Integrate cybersecurity workforce personnel into information systems life cycle development processes'),
('T1484', 'Establish testing specifications and requirements'),
('T1485', 'Prepare after action reviews (AARs)'),
('T1486', 'Process forensic images'),
('T1487', 'Perform file and registry monitoring on running systems'),
('T1488', 'Enter digital media information into tracking databases'),
('T1489', 'Correlate incident data'),
('T1490', 'Prepare cyber defense toolkits'),
('T1491', 'Design data management systems'),
('T1492', 'Integrate laws and regulations into policy'),
('T1493', 'Troubleshoot prototype design and process issues'),
('T1494', 'Recommend vulnerability exploitation functional and security-related features'),
('T1495', 'Recommend vulnerability mitigation functional- and security-related features'),
('T1496', 'Develop reverse engineering tools'),
('T1497', 'Determine supply chain cybersecurity requirements'),
('T1498', 'Determine if cybersecurity requirements included in contracts are delivered'),
('T1499', 'Integrate public key cryptography into applications'),
('T1500', 'Install systems and servers'),
('T1501', 'Update systems and servers'),
('T1502', 'Troubleshoot systems and servers'),
('T1503', 'Evaluate platforms managed by service providers'),
('T1504', 'Manage organizational knowledge repositories'),
('T1505', 'Analyze cybersecurity threats for counter intelligence or criminal activity'),
('T1506', 'Analyze software and hardware testing results'),
('T1507', 'Determine user requirements'),
('T1508', 'Plan cybersecurity architecture'),
('T1509', 'Analyze feasibility of software design within time and cost constraints'),
('T1510', 'Preserve digital evidence'),
('T1511', 'Identify alleged violations of law, regulations, policy, or guidance'),
('T1512', 'Perform periodic system maintenance'),
('T1513', 'Conduct trial runs of programs and software applications'),
('T1514', 'Determine accurate security levels in programs and software applications'),
('T1515', 'Manage network access control lists on specialized cyber defense systems'),
('T1516', 'Detect concealed data'),
('T1517', 'Deliver training courses'),
('T1518', 'Develop organizational cybersecurity strategy'),
('T1519', 'Design system security measures'),
('T1520', 'Update system security measures'),
('T1521', 'Develop enterprise architecture'),
('T1522', 'Determine if systems meet minimum security requirements'),
('T1523', 'Design organizational knowledge management frameworks'),
('T1524', 'Implement organizational knowledge management frameworks'),
('T1525', 'Maintain organizational knowledge management frameworks'),
('T1526', 'Identify responsible parties for intrusions and other crimes'),
('T1527', 'Define baseline system security requirements'),
('T1528', 'Develop software system testing and validation procedures'),
('T1529', 'Create software system documentation'),
('T1530', 'Develop local network usage policies and procedures'),
('T1531', 'Determine compliance with local network usage policies and procedures'),
('T1532', 'Develop procedures for system operations transfer to alternate sites'),
('T1533', 'Test failover for system operations transfer to alternative sites'),
('T1534', 'Develop cost estimates for new or modified systems'),
('T1535', 'Develop implementation guidelines'),
('T1537', 'Determine if cybersecurity training, education, and awareness meet established goals'),
('T1538', 'Resolve customer-reported system incidents and events'),
('T1539', 'Analyze organizational cybersecurity posture trends'),
('T1540', 'Develop organizational cybersecurity posture trend reports'),
('T1541', 'Develop system security posture trend reports'),
('T1542', 'Document original condition of digital evidence'),
('T1543', 'Develop cybersecurity policies and procedures'),
('T1544', 'Create definition activity documentation'),
('T1545', 'Create architecture activity documentation'),
('T1546', 'Provide inspectors general, privacy officers, and oversight and compliance with legal analysis and decisions'),
('T1547', 'Determine compliance with cybersecurity policies and legal and regulatory requirements'),
('T1548', 'Determine adequacy of access controls'),
('T1549', 'Evaluate the impact of legal, regulatory, policy, standard, or procedural changes'),
('T1550', 'Execute disaster recovery and continuity of operations processes'),
('T1551', 'Prosecute cybercrimes and fraud committed against people and property'),
('T1552', 'Identify cyber workforce planning and management issues'),
('T1553', 'Address cyber workforce planning and management issues'),
('T1554', 'Recommend enhancements to software and hardware solutions'),
('T1555', 'Implement cyber defense tools'),
('T1556', 'Identify system and network protection needs'),
('T1557', 'Implement security measures for systems and system components'),
('T1559', 'Resolve vulnerabilities in systems and system components');
