INSERT INTO tasks (code, description) VALUES
('T0006', 'Advocate organization''s official position in legal and legislative proceedings'),
('T0020', 'Develop content for cyber defense tools'),
('T0067', 'Develop architectures or system components consistent with technical specifications'),
('T0068', 'Develop data standards, policies, and procedures'),
('T0077', 'Develop secure code and error handling'),
('T0080', 'Develop test plans to address specifications and requirements'),
('T0081', 'Diagnose network connectivity problems'),
('T0084', 'Employ secure configuration management processes'),
('T0101', 'Evaluate the effectiveness and comprehensiveness of existing training programs'),
('T0116', 'Identify organizational policy stakeholders'),
('T0122', 'Implement security designs for new or existing systems'),
('T0124', 'Incorporate cybersecurity vulnerability solutions into system designs (e.g., Cybersecurity Vulnerability Alerts)'),
('T0126', 'Install or replace network hubs, routers, and switches'),
('T0129', 'Integrate new systems into existing network architecture'),
('T0137', 'Maintain database management systems software'),
('T0141', 'Maintain information systems assurance and accreditation materials'),
('T0153', 'Monitor network capacity and performance'),
('T0164', 'Perform cyber defense trend analysis and reporting'),
('T0167', 'Perform file signature analysis'),
('T0168', 'Perform data comparison against established database'),
('T0172', 'Perform real-time forensic analysis (e.g., using Helix in conjunction with LiveView)'),
('T0173', 'Perform timeline analysis'),
('T0179', 'Perform static media analysis'),
('T0182', 'Perform tier 1, 2, and 3 malware analysis'),
('T0193', 'Process crime scenes'),
('T0220', 'Resolve conflicts in laws, regulations, policies, standards, or procedures'),
('T0226', 'Serve on agency and interagency policy boards'),
('T0235', 'Translate functional requirements into technical solutions'),
('T0237', 'Troubleshoot system hardware and software'),
('T0262', 'Employ approved defense-in-depth principles and practices (e.g., defense-in-multiple places, layered defenses, security robustness)'),
('T0271', 'Develop cybersecurity designs to meet specific operational needs and environmental factors (e.g., access controls, automated applications, networked operations, high integrity and availability requirements, multilevel security/processing of multiple classification levels, and processing Sensitive Compartmented Information)'),
('T0274', 'Create auditable evidence of security measures'),
('T0292', 'Recommend computing environment vulnerability corrections'),
('T0299', 'Identify network mapping and operating system (OS) fingerprinting activities'),
('T0309', 'Assess the effectiveness of security controls'),
('T0311', 'Consult with customers about software system design and maintenance'),
('T0330', 'Maintain assured message delivery systems'),
('T0349', 'Collect metrics and trending data'),
('T0383', 'Program custom algorithms'),
('T0397', 'Perform Windows registry analysis'),
('T0412', 'Conduct import/export reviews for acquiring systems and software'),
('T0422', 'Implement data management standards, requirements, and specifications'),
('T0431', 'Check system hardware availability, functionality, integrity, and efficiency'),
('T0437', 'Correlate training and learning to business or mission requirements'),
('T0459', 'Implement data mining and data warehousing applications'),
('T0460', 'Develop and implement data mining and data warehousing programs'),
('T0495', 'Manage Accreditation Packages (e.g., ISO/IEC 15026-2)'),
('T0510', 'Coordinate incident response functions'),
('T0512', 'Perform interoperability testing on systems exchanging electronic information with other systems'),
('T0513', 'Perform operational testing'),
('T0531', 'Troubleshoot hardware/software interface and interoperability problems'),
('T0542', 'Translate proposed capabilities into technical requirements'),
('T0569', 'Answer requests for information'),
('T0685', 'Evaluate threat decision-making processes'),
('T0686', 'Identify threat vulnerabilities'),
('T0698', 'Facilitate continuously updated intelligence, surveillance, and visualization input to common operational picture managers'),
('T0707', 'Generate requests for information'),
('T0718', 'Identify intelligence gaps and shortfalls'),
('T0734', 'Issue requests for information'),
('T0751', 'Monitor open source websites for hostile content directed towards organizational or partner interests'),
('T0775', 'Produce network reconstructions'),
('T0818', 'Serve as a liaison with external partners'),
('T0845', 'Identify cyber threat tactics and methodologies'),
('T0898', 'Establish an internal privacy audit program'),
('T0934', 'Identify stakeholder assets that require protection'),
('T0937', 'Determine the placement of a system within the enterprise architecture'),
('T0942', 'Identify the types of information to be processed, stored, or transmitted by a system'),
('T0960', 'Monitor changes to a system and its environment of operation'),
('T1008', 'Prepare and deliver education and awareness briefings'),
('T1009', 'Create a cybersecurity awareness program'),
('T1010', 'Communicate enterprise information technology architecture'),
('T1011', 'Apply standards to identify safety risk and protect cyber-physical functions'),
('T1012', 'Expand network access'),
('T1013', 'Conduct technical exploitation of a target'),
('T1014', 'Determine if security incidents require legal action'),
('T1015', 'Identify roles and responsibilities for appointed Communications Security (COMSEC) personnel'),
('T1016', 'Identify Communications Security (COMSEC) incidents'),
('T1017', 'Report Communications Security (COMSEC) incidents'),
('T1018', 'Identify in-process accounting requirements for Communications Security (COMSEC)'),
('T1019', 'Determine special needs of cyber-physical systems'),
('T1020', 'Determine the operational and safety impacts of cybersecurity lapses'),
('T1021', 'Review cyber defense service provider reporting structure'),
('T1022', 'Review enterprise information technology (IT) goals and objectives'),
('T1023', 'Identify critical technology procurement requirements'),
('T1024', 'Implement organizational security policies and procedures'),
('T1025', 'Implement organizational training and education policies and procedures'),
('T1026', 'Determine procurement requirements'),
('T1027', 'Integrate organizational goals and objectives into security architecture'),
('T1028', 'Research new vulnerabilities in emerging technologies'),
('T1029', 'Implement organizational evaluation and validation criteria'),
('T1030', 'Estimate the impact of collateral damage'),
('T1031', 'Implement intelligence collection requirements'),
('T1035', 'Determine how threat activity groups employ encryption to support their operations'),
('T1036', 'Integrate leadership priorities'),
('T1038', 'Integrate organization objectives in intelligence collection'),
('T1039', 'Identify network artifacts'),
('T1041', 'Determine impact of software configurations'),
('T1043', 'Determine staffing needs'),
('T1046', 'Assess operation performance'),
('T1047', 'Assess operation impact');
